ManageIQ/manageiq-pods

templates/miq-template.yaml
- Changed memcached image to use miq-memcached (centos7 based)
- Added template parameters for memcached (memory_size and max_conn)
- Adjusted memcached IS name to miq-memcached for consistent naming
=> miq-template cleanup after memcached merge

images/miq-memcached/container-entrypoint, templates/miq-template.yaml
@bazulay @bdunne
This will allow the user to deploy the memcached pod with customized slab_page_size parameter, as promised in #10075 for OpenShift builds :smiley:
=> Add memcached slab_page_size param support on template and image

templates/miq-template.yaml
- Rolling has issues with database concurrency when upgrading a miq-app deployment, switching back to recreate
=> Change Deployment Strategy for miq-app to Recreate

README.md, miq-pv-app-example.yaml
The manageiq template [requires an application volume](https://github.com/fbladilo/miq-on-openshift/blob/master/templates/miq-template.yaml#L60-L69) in addition to the postgres volume but does not include the creation of the volume in the instructions.
This adds a volume for manageiq to use and updates the README
=> add app pv instructions and yaml

templates/miq-template.yaml
- Prevent service pods from using latest tag on deployments, it is safer this way
- The miq-app deployment image will continue to use latest tag since we can only build master
=> Fix versions for miq-postgresql and miq-memcached on template

images/miq-app/docker-assets/appliance-initialize.sh, images/miq-app/docker-assets/container-deploy-common.sh
- run_hook now accepts a script name argument, it is meant to be executed at any stage of the deployment
- two default entries were added for the upgrade procedure pre-upgrade and post-upgrade
- if a script is not found, run_hook returns 1 and the deployment continues
- if a script is found but exits abnormally, the deployment fails and exit 1
=> Re-work run_hook function to accept a script name argument

images/miq-app/docker-assets/appliance-initialize.service, images/miq-app/docker-assets/appliance-initialize.sh, templates/miq-template.yaml
- Default APPLICATION_INIT_DELAY parameter is 30 seconds to allow rest of services to settle
- /bin/appliance-initialize.sh now calls sleep instead of appliance-initialize systemd service unit file
- Removed pre_upgrade_hook call from /bin/appliance-initialize.sh (function no longer valid)
=> Add APPLICATION_INIT_DELAY as a template parameter and minor fixes

images/miq-app/docker-assets/appliance-initialize.sh, images/miq-app/docker-assets/container-deploy-common.sh
- write_deployment_info has been enhanced to handle PV deployment info file updates once an upgrade is successful
- write_deployment_info call added to deployment upgrade case procedure on appliance-initialize.sh
Sample simulated upgrade from darga to euwe
```
[root@manageiq-1-qw200 /]# /bin/appliance-initialize.sh
== Checking deployment status ==
== Found existing deployment configuration ==
== Restoring existing database configuration ==
== Starting Upgrade ==
== Initializing PV data backup ==
== Calling Deployment Hook ==
Hook script pre-upgrade not found, skipping
== Restoring PV data symlinks ==
/var/www/miq/vmdb/REGION symlink is already in place, skipping
/var/www/miq/vmdb/GUID symlink is already in place, skipping
/var/www/miq/vmdb/config/database.yml symlink is already in place, …
```
=> Enhance write_deployment_info to handle upgrade

images/miq-postgresql/9.5/Dockerfile
The RPM is now hosted in a different repo.
(https://github.com/ManageIQ/manageiq/pull/11951)
=> Rename rh-repmgr95 to rh-postgresql95-repmgr

images/miq-app/Dockerfile
With new npm (v3.10) in EPEL, updating itself is no longer needed
and 'npm install' no longer works after npm itself is updated
(https://github.com/ManageIQ/manageiq/pull/11849)
=> Remove npm updating itself

templates/miq-template.yaml
- Increased timeout to 1200 seconds on miq-app deployment strategy
- Increase liveness check timeout to 480 seconds (8mins)
This prevents issues on first time deployment where the miq-app image
is being downloaded and the default recreate strategy timeout of 600 seconds
is not long enough for a complete a successful deployment.
Tested on OCP 3.3
=> Increase miq-app deployment strategy timeout

templates/miq-template-monolithic.yaml
- Updated template metadata and tags
- Modified image stream source to track upstream MIQ image
- Added DATABASE_VOLUME_CAPACITY parameter to template
- Relaxed strategy and liveness checks timeouts
- Switched to Recreate strategy
- Added APPLICATION_DOMAIN parameter to template
=> Update monolithic template to use upstream MIQ image and other fixes

images/miq-app/docker-assets/appliance-initialize.sh, images/miq-app/docker-assets/container-scripts/container-deploy-common.sh
- Added check_db_status to ensure readiness of postgresql POD before trying to initialize
- Function uses PG provided pg_isready to perform connectivity tests
- Database hostname is supplied by OpenShift template parameters
=> Add check_db_status function to container-deploy-common

images/miq-app/Dockerfile
- Reconcile miq-app with monolithic image systemd cleanup, see #12103 for details
- Removed unnecessary commented PG volume line from miq-app
=> Dockerfile miq-app systemd base image cleanup

templates/miq-template.yaml
- Add svc dependency annotations, allows automatic grouping of services and deps on web console
- Suggestion by Openshift team
=> Add svc dependency annotations

templates/miq-template.yaml
- Hint OpenShift via resource request about our minimum memory needed to run the miq-app container
- 4Gi is the default requested mem, it should be good enough for an initial deployment
- Min memory is customizable via the MEMORY_APPLICATION_MIN parameter
=> Add minimum memory request to miq-app pod

templates/miq-template.yaml
- The PG dc initialdelay is too aggressive for certain OCP cluster hardware configurations
- Set 15 seconds for initialdelay on readiness and 1 minute for liveness
=> Relax PG pod deployment config probes initialdelay

templates/miq-template.yaml
- Added image tag paremeters for all pods deployed, allows a user to request specific tags on deployment
=> Parametize image tags on template

templates/miq-template.yaml
Use manageiq/manageiq-pods images built in Docker Hub.
All 3 images come from 'manageiq-pods' and each image will have different tag which contains the name of the image ('app', 'memcached' or 'postgresql').
=> Use manageiq/manageiq-pods images

images/miq-app/docker-assets/container-scripts/container-deploy-common.sh
- Do not rely on v2_key present on image, always restore v2_key from persistent volume on redeploy/upgrade.
=> Ensure DB v2_key is always restored on upgrade/redeploy

images/miq-app/Dockerfile, images/miq-app/docker-assets/container-scripts/container-deploy-common.sh
- Removed bin/setup call on Dockerfile
- Modified appliance_console_cli to create a valid key during initialization
=> Do not copy dev v2_key during image build

images/miq-postgresql/9.5/Dockerfile
This repo is now versioned so that we can maintain different package versions for different MIQ versions.
This also upgrades the pglogical package to version 1.2.1
Related PRs:
https://github.com/ManageIQ/manageiq-appliance-build/pull/186
https://github.com/ManageIQ/manageiq/pull/13070
@simaishi @fbladilo please review
=> Update the repo location for MIQ pglogical and repmgr packages

templates/miq-template.yaml
- Split the single miq-images ImageStream into 3 independent ImageStreams (one per image)
- Allows a user to reference a different IMG_NAME for PG/Memcached that will not be overriden by miq-images IS
- By default all ImageStreams point to the same registry and default IMG_NAME_* to manageiq-pods
=> Allow better flexibility for IMG_NAME params using multiple IS

templates/miq-template.yaml
- Removed IMAGE_REGISTRY param from template IS, now REGISTRY must be bundled with IMG_NAME
- This should allow each individual IS to work with independent IMAGE_NAME and REGISTRY if desired
=> Remove IMAGE_REGISTRY param in favor of IMG_NAME parameters for each pod

README.md
This change adds the documentation to build images on OpenShift:
```
```
The `new-app` example presented here is a good start but it is not handling the `ImageStream` because it depends on the upcoming work to split the streams for each `dc`.
cc @fbladilo @bazulay
=> Add documentation to build images on OpenShift

templates/miq-template.yaml
- Set a default min RAM resource requests for all pods
- Set a default max RAM allowed to consume for all pods
- Set a default min CPU resource requests for all pods
- All defaults are parametized and can be controlled at initial deployment
- Allow CPU time to be burstable but request a minimum allocation (expressed in millicores)
=> Set and parametize resource requests and limits for all pods

images/miq-app/docker-assets/appliance-initialize.sh, images/miq-app/docker-assets/container-scripts/container-deploy-common.sh
- Always perform an initial backup once PV is initialized
- Do not process server logs on upgrade case backups, fixes #99
- Renamed old sync_pv function to init_pv, which must only run once *per* deployment
- Refactor sync_pv function to handle proper syncing of PV data on pod termination
=> Enhance backup infrastructure and minor fixes

README.md, miq-pv-app-example.yaml, miq-pv-example.yaml, templates/miq-template.yaml
- Increase default volume capacity to 5GB for App pod, 15GB DB pod, this is more realistic.
- Updated docs and sample templates.
- Fixes #106
=> Update template default capacities for DB and Application PVs

images/miq-app/Dockerfile
- Install and enable logrotate on miq POD image
- Install cronie and enable service as a dependency
- Resolves #98
- Logrotate configuration comes from manageiq-appliance repo
- Daily (max 14 day) log rotation by default
=> Enable logrotate on MIQ image

templates/miq-template.yaml
- Switch liveness probe to tcpsocket to resolve miq pod restart issue in the event of DB outage
- Switch readiness probe to HTTPs instead HTTP
=> Enhance health probes on MIQ pod (liveness/readiness)

README.md, images/miq-app/Dockerfile, images/miq-app/docker-assets/appliance-initialize.sh, images/miq-app/docker-assets/container-scripts/container-deploy-common.sh, miq-pv-db-example.yaml, miq-pv-region-example.yaml, miq-pv-server-example.yaml, templates/miq-template.yaml
- Replaced MIQ template Deployments in favor of Petsets
- miq-app image Dockerfile updated to reflect a 2-volume deployment (region/server)
- Applied necessary changes to container-deploy-common.sh to handle the 2-volume configuration
- Created function to detect a new_replica deployment on container-deploy-common.sh
- Created function to handle REGION join for new replicas on container-deploy-common.sh
- Added logic on appliance-initialize.sh to call a new_replica case
- Updated NFS PV templates to reflect new storage configuration
- Updated all documentation to reflect new procedures and added "Scale" section
=> Scale MIQ appliances using PetSets

templates/miq-template.yaml
- Allow user to deploy desired number of MIQ replicas using parameters
=> Parametize APPLICATION_REPLICA_COUNT for petset controller

templates/miq-template.yaml
- Create secret template object along with necessary keys
- Randomize DB password template parameter
- Expose DB password secret as a ENV variable for deployment use
- Fixes #105
=> Randomize DB password by default and store on secret

images/miq-app/Dockerfile
- Collapse 10+ layers into 1
- Collapse Atomic/Openshift layers into 1
- Move static LABEL layer on top of manifest to benefit caching
- Remove Atomic actionable labels since they target a local PG installation
- Remove unnecessary symlink to docker_initdb
=> Optimize layering on miq-app Dockerfile

images/miq-app/Dockerfile
- See https://github.com/ManageIQ/manageiq/pull/14605
- OpenShift honors STOPSIGNAL on termination/shutdown
- Allows container to shutdown gracefully and terminate all connections appropiately
=> Systemd set correct STOPSIGNAL on podified MIQ image

images/miq-app/Dockerfile
- Issue a yarn cache clean after SUI build
- Reduces image size by 300MB
=> MIQ POD cleanup yarn cache

README.md, templates/miq-template.yaml
@bazulay @carbonin @simaishi Please review, controller name change and documentation update, tested on latest OCP 3.5. We now have `oc scale` support. See sample below : 
```
oc version
oc v3.5.5.5
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://franco-ocp-master.e2e.bos.redhat.com:8443
openshift v3.5.5.5
kubernetes v1.5.2+43a9be4
[root@franco-ocp-master franco]# oc get pods
NAME                 READY     STATUS    RESTARTS   AGE
manageiq-0           1/1       Running   0          11m
memcached-1-p80t3    1/1       Running   0          10m
postgresql-1-c8rs2   1/1       Running   0          10m
[root@franco-ocp-master franco]# oc scale statefulset manageiq --replicas=2
statefulset "manageiq" scaled
[root@franco-ocp-master franco]# oc get statefulset …
```
=> Migrate petset to statefulsets

README.md
Provide name and password in the 'verify setup successful' section so admins can browse the web interface without having to lookup other documentation.
=> Include default name and password

README.md, templates/miq-template-ext-db.yaml
- Created new template excluding unncessary PG pod objects
- Added endpoints object and re-configured PG svc
- Remote endpoints parametized via DATABASE_SERVER_IP
- Updated documentation to reflect new deployment option
- PG server must be prepared for MIQ before attempting to use this template
=> Deploy MIQ using external PG database

images/miq-app/Dockerfile
The ruby part of this image doesn't change nearly as much as the miq specific bits.
If we create a separate ruby container and layer miq on top of it, we can get faster build times and make development a lot faster.
ref:
https://github.com/ManageIQ/container-ruby
https://hub.docker.com/r/manageiq/ruby/builds/
=> Separate ruby container

images/miq-app/docker-assets/container-scripts/container-deploy-common.sh, images/miq-app/docker-assets/container.data.persist
container.data.persist now only contains files for the server.
All region data is already handled by other symlinks / rsyncs.
=> Remove database.yml, REGION and v2_key from container.data.persist file

images/miq-app/Dockerfile
The container scripts are the only place this is used so the Docker
ENV directive should be enough.
=> Remove duplicate APP_ROOT environment variable

README.md, images/miq-app/Dockerfile, images/miq-app/docker-assets/appliance-initialize.sh, images/miq-app/docker-assets/container.data.persist, images/miq-app/docker-assets/entrypoint, templates/miq-template.yaml
This allows us to move away from some of the unpleasantness that systemd enforces when running in a container.
In particular this allows us to carry our environment through to the server process.
This PR also handles some of the fallout from this change, namely:
- Consolidation of ENVVARs
- Creation of the server ssl certificate (previously done in [evmserver.sh](https://github.com/ManageIQ/manageiq-appliance/blob/master/LINK/usr/bin/evmserver.sh#L10))
For this to work properly I still need to start `httpd` manually on the command line. /cc @bdunne
=> Remove systemd in favor of dumb-init for process management

images/miq-app/Dockerfile
We can ignore the services shipped in the base image now that we are not starting systemd at all..
=> Remove more systemd stuff

images/miq-app/docker-assets/appliance-initialize.sh
All other cases should restore the cert from the PV
=> Only generate the server certificate on new deployments.

images/miq-app/Dockerfile
Builds were failing with the following error:
`node: error while loading shared libraries: libhttp_parser.so.2: cannot open shared object file: No such file or directory`
This resolves that issue
/cc @simaishi @fbladilo
=> Fix the node dependency on libhttp_parser

images/miq-app/docker-assets/appliance-initialize.sh, images/miq-app/docker-assets/container-scripts/container-deploy-common.sh, templates/miq-template-ext-db.yaml, templates/miq-template.yaml
We shouldn't edit settings.yml as it's the default shipping with the product.
=> Set memcached server override in ENV["MEMCACHED_SERVER"] rather than sed

templates/miq-template-ext-db.yaml
This was removed in e496ce5ba305a74f3c2233414352b737e7453fc5 but is still needed
=> Add the db service back to the app pod in the external db template

images/miq-app/docker-assets/appliance-initialize.sh, images/miq-app/docker-assets/container.data.persist, templates/miq-template-ext-db.yaml, templates/miq-template.yaml
This httpd image will be the front-end for all incoming requests.
- It will handle SSL for now (until it is moved into the route)
- It will proxy to the correct services.
- In the future it will handle all of the auth as well.
=> Add a httpd front end

images/miq-app/docker-assets/appliance-initialize.sh
This was causing the deployment to always fail after #162 was merged
=> Check the exit status of the rake task rather than cert generation

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
This is required so that it can write its config files and logs
Additionally we will need at least root when we add auth to this pod
=> Use the miq-anyuid scc for the httpd pod

images/miq-app-frontend/Dockerfile, images/miq-app-frontend/docker-assets/check-dependent-services.sh, images/miq-app/Dockerfile, images/miq-app/docker-assets/appliance-initialize.sh, images/miq-app/docker-assets/check-dependent-services.sh, images/miq-app/docker-assets/entrypoint, templates/miq-template-ext-db.yaml, templates/miq-template.yaml
Depends on https://github.com/ManageIQ/manageiq/pull/15470
The frontend ManageIQ pod will receive all web traffic, all frontend replicas must run the UI, API and WS roles (no change here).
Backend replicas will not receive any UI / API / WS requests, so those roles should not be enabled by default.  Backend replicas should also wait for the frontend service to become available before attempting to start the application.  Backend replicas should be set to 0 by default and users can scale it based on their needs.
This change allows us to scale with a smaller footprint since we usually need more MiqServers for operations and inventory roles than for UI/API roles.
=> Split front-end and back-end containers

README.md, templates/miq-template-ext-db.yaml, templates/miq-template.yaml
This PR adds a new service account for the manageiq application pod which is intended to have edit and view roles for the namespace the project is running in.
This will allow the app pod itself to scale other pods within the project up and down.
The plan is to use this ability to only scale the ansible pod when it is needed (when the role is enabled).
=> Allow server to control ansible pods

templates/miq-template.yaml
They will be namespaced by the pod name, so no collision is expected
i.e.
manageiq-server-manageiq-0
manageiq-server-manageiq-backend-0
=> The volumeMount and volumeClaimTemplate need to match

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
Without this, you get a not so helpful error:
```
pet: manageiq-backend-0, error: Pod "manageiq-backend-0" is invalid: metadata.annotations[pod.beta.kubernetes.io/subdomain]: Invalid value: "": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or '123-abc')
```
=> If serviceName is not provided, it gets set to '' which is invalid

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
This is required for them to control and view other pods in the project such as the embedded ansible pod.
Without this change, if the embedded ansible role were enabled on a "server" running on a backend pod we would fail.
=> Add the miq-orchestrator service account to the backend pods

templates/miq-template-ext-db.yaml
@carbonin @bdunne 
- We use 5432 for internal PG communication in OpenShift, do not set external endpoint PORT on url
- Resolves #177
=> Do not set remote endpoint PORT on database-url on ext template

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
- Increase default recreate strategy to 1200 (20 mins) from 600
- Allows httpd to be more patient with frontend statefulset seeding
=> Increase default httpd recreate strategy timeout

templates/miq-template.yaml
@carbonin @bdunne Please review guys..
- Configmap object created with MIQ default overrides settings
- Configmap is injected as a volume into /var/lib/pgsql/conf.d by default
- POSTGRESQL_CONFIG_DIR supplied to on template to allow flexibility on dir location
- Related to PR : https://github.com/ManageIQ/container-postgresql/pull/2
- PG image will pickup and do an include_dir if the directory is found
The most important piece is that the configuration is externalized and parametized. A user for instance can oc edit configmap , change parameter, oc rollout latest postgresql and be done. Configs can be stacked and multiple *.confs can be placed in directory , PG will process them all.
=> Allow PG MIQ configuration overrides via configmap

templates/miq-template.yaml
@carbonin @bdunne Follow up on this one...
- Provide reasonable minimum default resource requests for a PG/MIQ deployment on OpenShift
- Increased shared_buffers to 1GB
- Increased minimum RAM resource request to 4GB
- References :
https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server
https://access.redhat.com/documentation/en-us/red_hat_cloudforms/4.5/html/deployment_planning_guide/introduction#virtual-hardware-requirements
The kubernetes scheduler will only attempt a pod placement on a node that satisfies the minimum request, the shared buffer calculation is taken from the PG tuning guide at 1/4 of the available RAM. In this case, we calculate from the minimum memory request (guaranteed) and not the max memory limit set by default at 8GB and enforced via cgroups.
=> Increase PG Pod resource requirements

images/miq-app-frontend/Dockerfile, images/miq-app/Dockerfile
This mirrors the changes in https://github.com/ManageIQ/manageiq/pull/15578
This fixes the failing backend builds like https://hub.docker.com/r/manageiq/manageiq-pods/builds/bz3gpfgj9kfwxpnber5pxdi/
=> Use the update:ui task rather than update:bower

README.md, templates/miq-backup-job.yaml, templates/miq-backup-pvc.yaml, templates/miq-pv-backup-example.yaml, templates/miq-restore-job.yaml
@carbonin @bdunne Please review, some considerations : 
- Depends on https://github.com/ManageIQ/container-postgresql/pull/3
- Jobs execute in restricted SCC, identical to PG pod
- Arbitrary UID is assigned by OpenShift at a per project level, jobs must run within the same project for succesful results
- Jobs overwrite the PG image ENTRYPOINT with target script to run
- Backup job uses an extra PV/PVC pair
- Restore job uses both volumes, production and backup in order to perform restoration via TAR
- Procedure based on https://bugzilla.redhat.com/show_bug.cgi?id=1459652
- Added yaml templates for all required objects
- Updated README with instructions, notes and sample usage
- Tested on OCP 3.5
=> Allow MIQ database backup and restore via OpenShift jobs

images/miq-app/Dockerfile
We need access to this repo to install the http-parser package which was removed from EPEL when RHEL 7.4 was released.
It will be available again when CentOS 7.4 is released, but that won't be for at least a few more weeks.
See https://bugzilla.redhat.com/show_bug.cgi?id=1481470 for more details
/cc @simaishi
=> Add the ManageIQ copr repo to the app image

teardown
Add external database app, more service accounts, and the PG config map to the teardown script.
With these changes you should get a "Success" message from `oc new-app` after running teardown.
Before, I would get a failure because the service accounts and config map already existed.
=> Add things to teardown

README.md, templates/miq-sysadmin.yaml, templates/miq-template-ext-db.yaml, templates/miq-template.yaml
Updating manageiq-pods so that it defines an miq-sysadmin scc and service account for the container-httpd pod.
This is needed for running httpd under systemd, a requirement for enabling external authentication.
=> Update to support foundational update of container-httpd for external authentication

README.md, templates/miq-template-ext-db.yaml, templates/miq-template.yaml
@carbonin @bdunne @simon3z @mberube9 Removes the IS objects and related triggers from deployment configs. Some of controllers/deployments were not affected since they either don't currently use them or don't support them (i.e statefulsets). With the following changes image pulls will start immediately without trigger intervention. 
We never took much advantage of what IS can give us, specially considering they were configured with external docker repositories by default without actively tracking changes.
This resolves the long standing and very intrusive master node config change for maxImagesBulkImportedPerRepository.
Related issues :  #191 and https://github.com/openshift/openshift-ansible/issues/4822
=> Remove IS and imagechange trigger from templates

README.md, teardown, templates/miq-template-ext-db.yaml, templates/miq-template.yaml
- Added new httpd-auth-configs config map to the templates
- mounted the new configmap for httpd pod as /etc/httpd/auth-conf.d
- updated teardown script to handle the new config map
=> Enhancement to support the httpd authentication configuration map.

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
While experimenting with redis-backed actioncable I found out that websockets aren't working at all because the configuration of the HTTPD pod's configuration.
=> Create separate reverse proxying for websocket connections

README.md, teardown, templates/miq-scc-httpd.yaml, templates/miq-template-ext-db.yaml, templates/miq-template.yaml
@carbonin @abellotti @bdunne @Fryguy Please review guys, see #213.
```
[root@franco-ocp-master manageiq-pods (reassign_sa_httpd_pod)]# oc version
oc v3.5.5.5
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://franco-ocp-master.e2e.bos.redhat.com:8443
openshift v3.5.5.5
kubernetes v1.5.2+43a9be4
[root@franco-ocp-master manageiq-pods (reassign_sa_httpd_pod)]# oc get pods | grep httpd
httpd-1-zp82b        1/1       Running   0          40m
[root@franco-ocp-master manageiq-pods (reassign_sa_httpd_pod)]# oc describe pods httpd-1-zp82b | grep "Security Policy"
Security Policy:	anyuid
[root@franco-ocp-master manageiq-pods (reassign_sa_httpd_pod)]# oc exec httpd-1-zp82b pidof httpd
111 110 109 108 107 105 37
```
=> Deploy HTTPD pod with anyuid SCC by default

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
- The httpd pod is considered alive if a httpd process is spawned
- The httpd pod is considered ready if a socket can be open on port 80
=> Enhance HTTPD pod liveness/readiness probes

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
We don't really need these and it will simplify productization if we just leave them out.
cc @simaishi
=> Remove names with miq or manageiq related to the ansible deployment

images/miq-app-frontend/docker-assets/check-dependent-services.sh, templates/miq-template-ext-db.yaml, templates/miq-template.yaml
Now that https://github.com/ManageIQ/manageiq/pull/16001 is merged we can remove the environment variables that were previously being used in place of the *_SERVICE_HOST ones.
=> Remove unnecessary service name environment variables

README.md, templates/miq-scc-sysadmin.yaml, templates/miq-template-ext-db.yaml, templates/miq-template.yaml
This allows us to use the same template on minishift as well as a full OpenShift cluster. Now the change that needs to be made based on environment is just in documentation steps rather than editing the template.
Technically, this always uses the miq-httpd service account for the httpd pod and allows the user to choose the scc assigned to that service account based on their environment. For minishift that scc will be miq-sysadmin and for the full cluster, it will be anyuid.
@fbladilo This is more what I was thinking would be a good fix for #213 
Now devs using minishift don't have to change the template (and deal with a dirty git status) to run on minishift.
=> Use httpd service account for all environments

README.md, templates/miq-pv-db-example.yaml, templates/miq-pv-server-example.yaml
This is a follow up to [#222 RFE/Question - Turn PV examples into templates](https://github.com/ManageIQ/manageiq-pods/issues/222)
----
[The current docs](https://github.com/ManageIQ/manageiq-pods#make-persistent-volumes-to-host-the-miq-database-and-application-data) describe creating the required PVs in terms of simply editing the provided [app](https://github.com/ManageIQ/manageiq-pods/blob/master/templates/miq-pv-server-example.yaml)/[db](https://github.com/ManageIQ/manageiq-pods/blob/master/templates/miq-pv-db-example.yaml) examples with the required NFS paths. This change turns creating PVs into a no-editing-required process by wrapping the PV objects in kube templates.
Using a template in this PR is pretty simple! No more editing required
* `DB_PV_SIZE` - **Defaults** to the …
=> Change wrap app/db PV definitions into kube templates

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
- Declared an HTTPD_AUTH_API service
- This provides us with HTTPD_AUTH_API_SERVICE_HOST and HTTPD_AUTH_API_SERVICE_PORT on all pods.
Related PRs:
- [ManageIQ/manageiq-pods PR# 204](https://github.com/ManageIQ/manageiq-pods/pull/204)
- [ManageIQ/container-httpd PR# 15](https://github.com/ManageIQ/container-httpd/pull/15)
- [ManageIQ/manageiq PR# 15881](https://github.com/ManageIQ/manageiq/pull/15881)
=> Added support for the httpd auth-api service

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
Changing all auth-api to dbus-api to reflect the new ManageIQ/dbus_api_service
=> Renaming auth_api to dbus_api service to reflect the new ManageIQ/dbus_api_service

images/miq-app-frontend/docker-assets/manageiq-http.conf
This goes along with the changes in https://github.com/ManageIQ/manageiq-appliance/pull/131
This should be merged after that patch so that the file actually exists.
=> Rename API redirects httpd conf file

README.md, templates/miq-template-ext-db.yaml, templates/miq-template.yaml
- Introduced HTTPD_AUTH_CONFIGURATION to select which authentication configuration files to include
- authentication.conf includes the configuration-* file based on HTTPD_AUTH_CONFIGURATION
- common configurations sections are shared by different types minimizing duplication.
- Introduced HTTPD_AUTH_KERBEROS_REALMS needed for kerberos authentication
=> Adding external authentication httpd configuration files

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
- Reconfigure liveness probe to use PID check of MIQ server process
- Reconfigure readiness probe to use TCP check on port 80 instead of HTTP code check
- Initial probe delays were not modified
The PID check is more effective, specially on initial deployments, liveness will succeed as long as MIQ Server is alive, this would prevent OpenShift from killing/restarting the pod unnecessarily when MIQ server is actually in the final stages of seeding and about to come up.
The initial delays for each probe were kept intact, these are heavily dependent on the performance of cluster nodes assigned for a MIQ deployment. Currently 3 mins for readiness and 8 mins for liveness.
=> Enhance app-frontend probes

README.md
- We require a minimum of PG 9.4 or 9.5 if replication is needed
=> Update external DB section with PG version requirements

images/miq-app/Dockerfile
Related PR: https://github.com/ManageIQ/manageiq-appliance-build/pull/245
=> [GAPRINDASHVILI] Lock bundler to 1.15.4

README.md
- Add reference to the httpd configmap generator in the external authentication configuration section.
=> Add reference to the httpd configmap generator

images/miq-app/Dockerfile
- Reconcile missing nfs-utils from upstream images (required for sched backup tasks)
- Enable rpcbind on image, required for auto-negotiated NFS v3 mounts
=> [FINE] Fix scheduled backup tasks using NFS

images/miq-app/docker-assets/appliance-initialize.sh, images/miq-app/docker-assets/container-scripts/container-deploy-common.sh, templates/miq-template-ext-db.yaml, templates/miq-template.yaml
* Defines new APPLICATION_ADMIN_PASSWORD param
* Adds necessary element to existing manageiq secrets object
* Adds shell function calling rails runner, seeds minimal models and changes password
* Function is called via appliance-initialize.sh, last step for new_deployment case
* By default password is set to default MIQ value but customizable as desired at deployment time
* Related to #237 
Usage : `oc new-app --template=manageiq -p APPLICATION_ADMIN_PASSWORD=mypasswd`
@carbonin @bdunne
=> Allow setting MIQ admin password during deployment

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
This commit changes the proxy directives added in #208 to rewrite rules which seem to play better with the existing rules put in place for auth.
Before this, notifications did not work properly and httpd processes were starting constantly and not exiting.
https://bugzilla.redhat.com/show_bug.cgi?id=1526601
Note:
This seems to have been working before 7e86fe9, but somehow the RewriteRule added there messes with the ws proxy.
@abellotti can you test auth out with this change?
@skateman does this make sense to you?
=> Make websockets work again

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
These objects will be created by the server process as they are
needed.
This way we can control what images are used and how they are deployed
from the ManageIQ code base rather than maintaining templates.
Additionally, users who are not using the embedded ansible role
will no-longer have an unused deployment config sitting in the project
=> Remove the embedded ansible objects from the template

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
Updated httpd application.conf config file so error_log and access_log also sent to the container's stdout/stderr.  This allows the httpd pod logs to be accessed via docker logs or oc logs.
=> Ensures httpd error_log and access_log are seen by docker or oc logs commands

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
I don't think we need this on the backend pod, right?
I also feel like the variable is a bit backwards, but don't want to set "USE_SECURE_SESSION" everywhere on the appliance.  Maybe this will be reversed in a future release?
=> Allow insecure session

templates/miq-template.yaml
This will be included into the main postgresql.conf automatically.
Because this path is tied directly to the implementation, there is no reason to expose it to the user as a parameter.
Requires https://github.com/ManageIQ/container-postgresql/pull/8
https://bugzilla.redhat.com/show_bug.cgi?id=1540957
=> Mount the configmap into the directory the new image expects

templates/miq-template.yaml
https://github.com/sclorg/postgresql-container/pull/232 changed the directory name from postgresql-config to postgresql-cfg.
Marking this as gap/yes and blocker as it will be both of those as soon as QE finds it.
=> Put the PG config map in the new new include location

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
=> Fix the external db template after merging #207

README.md, teardown, templates/miq-template-ext-db.yaml, templates/miq-template.yaml
These can be created as template objects rather than making the user create them manually through the command line.
=>  Add rolebindings for the orchestrator to the templates

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
The default (rolling) will allow two orchestrators to run at the same
time which will cause a bunch of confusion for too many reasons to list
here
=> Use the recreate deployment strategy for the orchestrator

images/miq-app/Dockerfile, images/miq-app/container-assets/miq_logs.conf
This PR adds the logrotate configuration to the app images and alters it so that it will correctly rotate the application logs. In the first commit, the initial file was taken from the [manageiq-appliance repo](https://github.com/ManageIQ/manageiq-appliance/blob/a04b2a8a2a96f7a801e4701cd9c8cd2492079d69/COPY/etc/logrotate.d/miq_logs.conf). Subsequent commits alter the file.
Before this PR logs were not being rotated because the free space check script was failing on the container filesystem. Because filesystem space is not really the concern of the container, the check was removed from this overwrite file.
https://bugzilla.redhat.com/show_bug.cgi?id=1560210
=> [GAPRINDASHVILI] Fix container logrotate

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
We are not going to get an official Artemis RPM or container image
in time for the hammer release, so we're going to remove these
for now.
=> [HAMMER] Remove artemis from the templates

README.md, templates/miq-template-ext-db.yaml, templates/miq-template.yaml
Adding support for OpenID-Connect
- auth-type: openid-connect
- new auth config parameters:
o HTTPD_AUTH_OIDC_PROVIDER_METADATA_URL   oidc-provider-metadata-url
o HTTPD_AUTH_OIDC_CLIENT_ID               oidc-client-id
o HTTPD_AUTH_OIDC_CLIENT_SECRET           oidc-client-secret
=> Adding support for OpenID-Connect

templates/miq-template.yaml
See: https://github.com/ManageIQ/manageiq-appliance/pull/201
=> Use the new repmgr preload library name

templates/miq-template.yaml
Addresses RFE: https://bugzilla.redhat.com/show_bug.cgi?id=1612814
=> [HAMMER] Changed template to add miq-log config map

images/miq-app/Dockerfile
As a part of the upgrade in https://github.com/ManageIQ/manageiq-appliance-build/pull/280
=> [HAMMER] Use the ruby 2.4 image

images/miq-app-frontend/Dockerfile, images/miq-app/Dockerfile
These changes have been made on the appliance side, but have been missing here for months.
Specifically, this PR updates to node 8, creates the `vmdb/log` directory when trying to create the `apache` log directory, and updates to bundler `>=1.16.2`
=> [HAMMER] Make builds work

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
https://www.pivotaltracker.com/n/projects/1610127/stories/160297262
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650583
This PR is one of two that will implement moving external authentication support from
the Apache module mod_auth_kerb to mod_auth_gssapi for the Openshift/podified build
The other PR is:
ManageIQ/container-httpd#38
=> Move from apache module mod_auth_kerb to mod_auth_gssap

images/miq-app-frontend/Dockerfile, images/miq-app/Dockerfile
The first PR to get master/ivanchuk up-to-date... Updated ruby, node and postgresql packages and a few minor cleanups. 
Trying to make just enough changes to get monolithic (which is built on top of podified) up and running first. So podified will still not work...
=> Update ruby, node and postgresql

images/miq-app/container-assets/container-scripts/container-deploy-common.sh
The find_by_* methods defined in manageiq repo has conflicts with
rails dynamic finding and now they have been changed to lookup_by_.
Switching the callers in this repo to the lookup_by_ methods.
Depend on ManageIQ/manageiq#19313
=> Switch find_by_* to lookup_by_*

templates/miq-template.yaml
We don't need pglogical any more as we're using the built-in logical
replication in postgres 10 and we never needed repmgr in this image.
=> Use the PG 10 image rather than our custom one.

templates/build-template.yaml
We can do this now that we merged the rearch branch back into master
=> Update the default build template ref to the pods master branch

templates/miq-template.yaml
Fix of PostgreSQL ConfigMap `${DATABASE_SERVICE_NAME}-configs`:
* `shared_preload_libraries = 'pglogical,repmgr'` from `templates/miq-template.yaml`
* as PostgreSQL 10 being used in `ivanchuk` release, those parameters are not required - if kept there, PostgreSQL does not start
* resolves issue https://github.com/ManageIQ/manageiq-pods/issues/346
=> [IVANCHUK] Template removal of pg shared_preload_librariers

README.md, bin/deploy, bin/teardown, templates/app/httpd.yaml, templates/app/memcached.yaml, templates/app/orchestrator.yaml, templates/app/postgresql.yaml, templates/app/rbac.yaml, templates/examples/minikube-pv.yaml
This PR makes all objects created by our templates usable with either Kubernetes or OpenShift.
The obvious changes here are DeploymentConfig objects become Deployments and the Route becomes an Ingress.
The more subtle changes are to do with ssl and security contexts ...
By default, in production mode, the manageiq application requires us to communicate over https. Previously, our ssl handling was done by the route and routes generated a self-signed cert and key pair for the user if one was not provided. An Ingress object does not. So one change was that if a secret didn't exist already to hold the cert and key, the deploy script creates a keypair and a secret.
For the httpd pod to run correctly it needs the SYS_ADMIN kernel capability. In openshift this was provided by either the custom …
=> Use kubernetes compatible objects

bin/build
Since build args overwritten won't be showing up in docker build log, print out the actual cmd being run.
=> Print out build args/tag used

bin/build, images/manageiq-ui-worker/Dockerfile, images/manageiq-ui-worker/container-assets/npm_registry/npm_registry_setup.sh, images/manageiq-ui-worker/container-assets/npm_registry/npm_yarn_registry_cleanup.sh, images/manageiq-ui-worker/container-assets/npm_registry/yarn_registry_setup.sh
Podified image version of https://github.com/ManageIQ/manageiq-appliance-build/pull/366
Scripts in container-assets/npm_registry were copied from manageiq-appliance-build and I made minor edits to make them work in this repo (e.g. no erb).
=> Add support to use non-default npm registry

images/miq-app-frontend/Dockerfile
Related PR: https://github.com/ManageIQ/manageiq-appliance-build/pull/342
`master` was updated as a part of @carbonin 's changes for the new architecture.
=> [IVANCHUK] Add yarn available-languages to ui-service build

images/manageiq-base-worker/container-assets/entrypoint
Previously this was preventing the worker from heartbeating over drb
but now that file-based heartbeat is the only option it is preventing
the worker from heartbeating at all which is causing the worker pods
to be constantly killed because of the liveness check.
Introduced in ManageIQ/manageiq@20f9cc5a493d5243a77c4e8b66f385bb9f491179
=> Remove the DISABLE_MIQ_WORKER_HEARTBEAT env var

images/manageiq-base-worker/container-assets/entrypoint
The --heartbeat parameter is required. Otherwise run_single_worker
will set DISABLE_MIQ_WORKER_HEARTBEAT
Additionally change from `rails runner` to `ruby` as the
run_single_worker script will source the environment correctly.
This also makes this entrypoint more similar to how we run
the same script from the appliance architecture.
=> Enable heartbeat more

bin/remove_images
I was hoping to find a command that can remove everything built by running `bin/build` (final images along with intermediate layers), but I couldn't find it.... so this will just delete images with a given tag.
On our build machine, I will setup a cron job to prune all `<none>:<none>` images separately.
=> Add a script to remove all images for a tag

templates/app/httpd.yaml
Nothing in these services will change at runtime and the name
maps directly to the contents of the httpd config.
=> Create the ui, api, and remote console services in templates

templates/app/orchestrator.yaml
This isn't needed as kube always provides a file mounted into the pod
with the current namespace.
Requires https://github.com/ManageIQ/manageiq/pull/19846
=> Remove the MY_POD_NAMESPACE env var from the orchestrator

bin/build, images/manageiq-base/Dockerfile
By using a multi-stage build we can include our secret in a build
arg but then only copy over the files we need, throwing away the
layers that contain the reference to the secret and leaving no trace
on the filesystem.
@sethrpeterson @bennett-white does this handle the case you were trying to solve?
=> Use multi-stage builds to remove need for secrets container

README.md, bin/deploy, parameters, templates/app/app-secrets.yaml, templates/app/httpd.yaml, templates/app/memcached.yaml, templates/app/orchestrator.yaml, templates/app/postgresql-secrets.yaml, templates/app/postgresql.yaml, templates/app/rbac.yaml
This PR adds a new parameter (`APP_NAME`) to the templates which allows for changing the name of the deployed application.
This solves part of https://github.com/ManageIQ/manageiq-pods/issues/360
=> Allow for changing the app name using a parameter

parameters, templates/app/orchestrator.yaml
This PR adds a parameter for a secret name to be used for the orchestrator and worker images.
This secret should be pre-created and contain the credentials for the registry specified in the `ORCHESTRATOR_IMAGE_NAMESPACE` parameter.
Additionally it removes the app name prefix for the orchestrator deployment.
https://github.com/ManageIQ/manageiq/issues/19699
=> Add IMAGE_PULL_SECRET parameter

images/manageiq-base/Dockerfile, images/manageiq-ui-worker/Dockerfile
This commit substitutes dnf for yum, installs ruby in the manageiq-base
image, and adds some packages that were missing from the base image.
Specifically:
hostname for the "hostname" command
iproute for the "ip" command
libxml2-devel for the nokogiri gem
make for building gems
openssl-devel for the nokogiri gem
redhat-rpm-config for building gems
wget for the "wget" command
xz for use with tar -J flag
=> Base images on ubi8

images/manageiq-base/Dockerfile
Adding this package fixes warnings like these:
bash: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
bash: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8)
As well as allows the monolithic image to initdb properly:
/etc/default/evm: line 26: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
/etc/default/evm: line 26: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8)
== Checking MIQ database status ==
** DB has not been initialized
** Launching initdb
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.
initdb: invalid locale settings; check LANG and LC_* environment variables
!! Failed to initdb
ref: …
=> Add glibc-langpack-en to solve locale issues

images/manageiq-base/Dockerfile
Previously GIT_HOST update would not persist between layers making it unable to pull the tarball when using GIT_AUTH
=> Update Dockerfile for GIT_AUTH

bin/build, images/manageiq-base/Dockerfile
Images are now built with ubi8 base, so switching to use nodejs from AppStream. The 'master' appliance is using v12 as of https://github.com/ManageIQ/manageiq-appliance-build/pull/381
=> Use nodejs:12 from AppStream

images/manageiq-base/Dockerfile
Set RUBY_GEMS_ROOT that used to come from ruby container image, which we no longer use.  Also added other gem clean up, same as appliance build.
=> Clean up gems after "bundle install"

bin/build
Without `--pull`, it uses the image on local machine if exists, and doesn't check to see if a newer version is available.
I only added the option for manageiq-base build so it will pick up the latest ubi8 image.  For manageiq-* images, I thought you'd want to use local copy if exists, even if that's older than what's on Docker hub.
=> Pull latest ubi8 image for build

bin/build, images/manageiq-base/Dockerfile
The idea here is that anything that needs to be overlayed onto
the source directories will be handled by this one script.
It should assume that it's running locally to the "build",
"app", "sui", and "appliance" directories and add whatever it
wants to those, knowing that they will be copied over to the final
image in the next stage.
Fixes #360
=> Add a hooks url for build-time customization

bin/deploy, parameters, templates/app/kafka-secrets.yaml, templates/app/kafka.yaml, templates/app/orchestrator.yaml
This adds deployments for kafka and zookeeper as well as the related
services, volume claims, and secrets.
The kafka pod is not scaleable as there is configuration that needs
to be done for multiple brokers.
Fixes https://github.com/ManageIQ/manageiq/issues/20007
cc @agrare
=> Add kafka for messaging

manageiq-operator/deploy/role.yaml
Currently we request a bunch of RBAC permissions that we don't need. Additionally the `role.yaml` does not contain the minimal permissions we need to create all the objects we attempt to create.
This PR adds what is missing and removes what isn't needed.
Fixes #407
=> Request only the permissions we need and make the operator work

manageiq-operator/README.md, manageiq-operator/deploy/operator.yaml
This puts the steps to build and run the operator in the README
instead of referencing the OpenShift documentation.
Additionally it reorders some of the sections to ensure that the
deployment works properly. Specifically, the CRD needs to be created
before the operator is deployed to the cluster. This also needs to be
done whether you are running locally or deploying the operator as
a pod in the cluster.
This is what I was looking for in https://github.com/ManageIQ/manageiq-pods/pull/402#discussion_r400887590
cc @gyliu513
=> Add the actual steps for using the operator to the README

manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
These were not useful and were not being persisted to the API server
This is part 1 of the fix to #417
=> Remove status fields

manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
This is built on https://github.com/ManageIQ/manageiq-pods/pull/418, so merge that first.
This PR does some style cleanup and makes some functions into methods where it makes sense.
Additionally it removes the CleanUpOrchestratedDeployments function as it wasn't needed. All of the objects created by the operator are removed automatically.
=> Clean up controller

manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/httpd.go, manageiq-operator/pkg/helpers/miq-components/memcached.go, manageiq-operator/pkg/helpers/miq-components/orchestrator.go, manageiq-operator/pkg/helpers/miq-components/postgresql.go
Names starting with an upper case letter are reserved for public
(or "extern") variables or functions. We shouldn't use them for
locals.
=> Use lower case for local variables

manageiq-operator/pkg/helpers/miq-components/generators.go
With the URLEncoding, we would get an error from our ruby code
complaining that the key was not 32 bytes. It seems the difference
in encoding was causing the issue.
=> Use StdEncoding rather than URLEncoding for creating the encryption key

manageiq-operator/pkg/helpers/miq-components/orchestrator.go, templates/app/orchestrator.yaml
We will use this to set up a controller reference for all of the
worker deployments this orchestrator pod creates. This will ensure
that the worker deployments are removed even if the orchestrator
is brought down abruptly.
Part of #428
=> Add the pod UID to the orchestrator

manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/httpd.go, manageiq-operator/pkg/helpers/tlstools/generate_crt.go
This PR sdds a field to the manageiq spec for the tls secret name to allow the user to provide a pre-created secret.
This will behave just like the postgres secret:
If it is not provided a new secret called "tls-secret" will be created.
That secret will be removed when the CR is removed.
If the name is provided, but the secret does not exist when the
app is deployed a new secret will be created with the provided
name and used. This secret will also be removed with the CR.
If the name of an existing secret is provided, it will be used
and will not be removed when the CR is removed.
Fixes #409
Additionally this PR cleans up the GenerateCrt function a bit.
=> Allow user to provide tls secret

manageiq-operator/pkg/helpers/miq-components/orchestrator.go, templates/app/orchestrator.yaml
This is also needed to set the owner reference on the worker
deployments.
Forgot to add this in #434
Part of #428
=> Add the pod name as an env var to the orchestrator

manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
Updated controller to watch all resources created by manageiq instance to make sure they have the same life cycle as manageiq instance.
=> Watch on all resource types in case of accidental deletion of resources

bin/teardown, manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/rbac.go, templates/app/rbac.yaml
This is more like how an operator works and allows us to control
the individual permissions given to the orchestrator.
Specifically the "edit" cluster role didn't include the ability to
set finalizers on pods. This was preventing us from using kubernetes
garbage collection to ensure that the worker deployments were cleaned
up whenever the orchestrator pod is brought down.
Part of #428
=> Define and use a role for the orchestrator

manageiq-operator/deploy/role.yaml
Before this change we were getting a permissions error because the
orchestrator was asking for more permissions than the operator had.
This commit makes the operator roles a superset of the orchestrator's
and removes the escalate verb from the operator role
ref: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#privilege-escalation-prevention-and-bootstrapping
=> Allow operator to deploy orchestrator role

manageiq-operator/README.md, manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/crds/manageiq.org_v1alpha1_manageiq_cr.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/httpd.go, manageiq-operator/pkg/helpers/miq-components/memcached.go, manageiq-operator/pkg/helpers/miq-components/orchestrator.go, manageiq-operator/pkg/helpers/miq-components/postgresql.go, manageiq-operator/pkg/helpers/miq-components/util.go
This PR allows some sensible defaults to be used for nearly all of the parameters in the manageiq CR. By doing this it also allows manageiq to be deployed more easily in resource constrained environments like Code Ready Containers. Specifically the defaults for the resource limits and requirements are to not set any limits or requirements. If any of the values are set they will be properly reflected in the deployment.
This also makes manageiq much easier to deploy. A valid CR is now just:
```yaml
apiVersion: manageiq.org/v1alpha1
kind: ManageIQ
metadata:
name: miq
spec:
applicationDomain: "miqproject.apps-crc.testing"
```
This prevents the user from needing to know about things like image location, and tags, while allowing them to continue to …
=> Use defaults for missing cr values

bin/teardown
Setting an APP_NAME parameter in the teardown script that defaults to `manageiq`. Deployments using a non-default APP_NAME in the parameters file will be able to use teardown without editing it. 
Requesting that this change goes into jansa as well.
=> add app_name parameter to teardown script

README.md, bin/deploy_on_minishift, bin/teardown, images/manageiq-base/Dockerfile, images/manageiq-ui-worker/Dockerfile, manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/rbac.go, templates/app/rbac.yaml
This makes the orchestrator and work pods run in the restricted scc rather than anyuid
A bunch of certifications require us not to run as root
in containers. Additionally the vast majority of the application
should run fine without root and the parts that need root are
typically things we can't do in containers anyway.
Specifically this changes the permissions of some directories to
allow the root group access which is what we'll be running as when
using the restricted scc in OpenShift
Related to https://github.com/ManageIQ/manageiq-pods/issues/442
Merge with https://github.com/ManageIQ/manageiq/pull/20095
=> Don't run the app as root

manageiq-operator/pkg/helpers/miq-components/httpd.go, manageiq-operator/pkg/helpers/miq-components/httpd_conf.go, templates/app/httpd.yaml
This will make switching in an httpd pod without root privileges
easier as it won't be able to bind to port 80
Requires https://github.com/ManageIQ/container-httpd/pull/45
Related to https://github.com/ManageIQ/manageiq-pods/issues/467
=> Use 8080 for httpd and 8081 for dbus api

images/manageiq-ui-worker/Dockerfile
Before this change, the image had some logs left over from the build
which did not have the group permissions we need to write to them
at runtime.
This lead to failures in the UI pod:
```
/usr/share/ruby/logger.rb:744:in `initialize': Permission denied @ rb_sysopen - /var/www/miq/vmdb/log/audit.log (Errno::EACCES)
```
=> Clear the app logs directory after all UI worker steps

images/manageiq-base/Dockerfile
The ubi repos are not versioned by minor version so we were pulling
in a later version from there which was incompatible with the earlier
version that we had available for the other net-snmp-* packages
from the CentOS repos.
This lead to errors such as:
```
Error:
Problem: package net-snmp-utils-1:5.8-12.el8_1.1.x86_64 requires net-snmp-libs(x86-64) = 1:5.8-12.el8_1.1, but none of the providers can be installed
- cannot install both net-snmp-libs-1:5.8-14.el8.x86_64 and net-snmp-libs-1:5.8-12.el8_1.1.x86_64
- cannot install the best candidate for the job
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
=> Pin the base image to ubi 8.1 and don't install net-snmp from ubi repos

manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/httpd.go
This PR changes the operator to deploy an httpd image which requires fewer privileges and does not run `systemd` when we don't need it. It also adds the image to this repo (which we may or may not want to move forward with).
When the `HttpdAuthenticationType` parameter is either `internal` or `openid-connect`, we will deploy the image without systemd and will not require the httpd sa to have anyuid or privileged scc access.
This handles the first two bullets of https://github.com/ManageIQ/manageiq-pods/issues/467
I'll open a separate patch to configure oidc using the operator.
My only open issues with this PR are the name of the new image and its location. I would prefer this image be the un-qualified `manageiq/httpd` image as it's the less complicated of the two and change the name of …
=> Only use httpd with systemd when necessary

README.md, bin/teardown, templates/app/httpd.yaml
We're now using a separate image to implement external auth. In the operator we can switch between these two images based on the parameters provided in the CR, but the templates don't give us that kind of flexibility.
I think it's a better user-experience to be able to deploy the templates out-of-the-box without needing admin privileges rather than having the full suite of external auth available.
=> Remove external auth from the template-based deployment

manageiq-operator/pkg/helpers/miq-components/httpd.go
In the non-privileged image httpd will be running as pid 1 so
the container will exit if the process comes down, making the
liveness check redundant.
Fixes #475
=> Only check for the httpd process in the privileged image

manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/httpd.go, manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
This PR changes the way the operator deploys the external auth configuration for the httpd pod.
Now, we only deploy exactly what is required for the authentication type specified in the CR.
Additionally there are now two options for deploying OIDC authentication.
1. What we had before minus the [httpd_configmap_generator](https://github.com/ManageIQ/httpd_configmap_generator)
- Previously a user would have to utilize the config map generator to translate their oidc url, client secret, and client id into a config map then overwrite the existing auth-configs created by the operator after the deployment finishes
- Now the url can be supplied as `oidcProviderURL` in the CR and a secret should be created with the keys `CLIENT_ID` and `CLIENT_SECRET` and the name supplied as `oidcClientSecret` …
=> Allow more flexible external auth configuration

manageiq-operator/pkg/helpers/miq-components/generators.go
This was present in the [original implementation]
(https://github.com/ManageIQ/manageiq-password/blob/f85e888fe60433390d0a1d5145889edc67437fdf/lib/manageiq/password.rb#L210-L213)
but was only needed because that code allowed for user-provided
passwords to be used as the encryption key. In our implementation
we are only using random bytes as the input so an extra sha sum
doesn't do anything to improve security.
Additionally this was triggering an issue in some static security
analysis tools.
=> Remove extra sha256 sum when generating the encryption key

manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/crds/manageiq.org_v1alpha1_manageiq_cr.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
This makes the user choose a better password than "smartvm"
without generating one that will be difficult to communicate back
to the user
=> Make the admin password required in the CR

README.md, images/manageiq-orchestrator/container-assets/entrypoint, manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/crds/manageiq.org_v1alpha1_manageiq_cr.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/helpers/miq-components/app-secret.go, manageiq-operator/pkg/helpers/miq-components/orchestrator.go, parameters, templates/app/app-secrets.yaml, templates/app/orchestrator.yaml
The application has logic to configure the initial user and
also allows for changing that user's password. The ability to set
the password from multiple places is error-prone and confusing
Fixes #499
=> Remove ability to set the admin user password

manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml, manageiq-operator/deploy/operator.yaml
These are based on my environment which showed this pattern of resource usage for the operator:
Fixes #490
=> Add resource limits and requests for the operator

manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/httpd.go, manageiq-operator/pkg/helpers/miq-components/kafka.go, manageiq-operator/pkg/helpers/miq-components/memcached.go, manageiq-operator/pkg/helpers/miq-components/orchestrator.go, manageiq-operator/pkg/helpers/miq-components/postgresql.go, manageiq-operator/pkg/helpers/miq-components/util.go
This adds cpu and memory request/limit settings to every component that was previously missing them. Before this change kafka and zookeeper had no resource requests or limits. The rest of the components were missing the cpu limit setting for some reason.
All additional settings still default to no limit/request so that things are more easily deployed to environments with limited resources.
=> Add missing resource requests and limits

manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
After this change, any request to the API with basic auth (including
the admin user name) will be rejected by httpd with a 401 return code.
Fixes #501
=> Disable admin user API access when enableApplicationLocalLogin is false

manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/helpers/miq-components/httpd.go, manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
A user can now provide a secret containing the CA certs necessary
for httpd to securely connect to the OIDC server.
If the secret name is specified in the CR the operator will mount
the secret to `/etc/pki/ca-trust/source/anchors`.
If the secret name is not specified, but oidc-connect authentication
type is selected, the operator will add the parameters required to
disable server validation when communicating with the OIDC server.
Fixes #507
=> Add oidcCaCertSecret parameter

templates/miq-template-ext-db.yaml, templates/miq-template.yaml
After the image rename, the deploy will fail with the non-init httpd
image.
=> [IVANCHUK] Change the httpd image to httpd-init

manageiq-operator/pkg/helpers/miq-components/orchestrator.go, templates/app/orchestrator.yaml
Set's the pull policy to `Always` for the orchestrator image. Allows `jansa-latest` or other tags that contain latest to be constantly pulled. 
Fixes https://github.com/ManageIQ/manageiq-pods/issues/518 
Requesting backport to jansa branch
=> Add policy for orchestrator

.gitignore, bin/build, images/manageiq-base/Dockerfile, images/manageiq-base/container-assets/create_local_yum_repo.sh, images/manageiq-ui-worker/Dockerfile
Built on top of #485.
Adding 2 options to bin/build:
- `-b` builds RPMs from scratch
- `-l` uses RPMs that exist locally (the expected directory structure is what `-b` produces: manageiq-base/rpms/\<arch\>/*rpm
Also, 2 env can be set for rpm build:
- `RPM_BUILD_OPTIONS` overrides [default rpm build options](https://github.com/ManageIQ/manageiq-rpm_build/blob/master/config/options.yml) (repo, branches, etc.) - this is the path to the directory where override options.yml is.
- `RPM_BUILD_IMAGE` sets rpm build container image name (default: manageiq/rpm_build)
Notes:
- Running with `-b` will remove previously built RPMs.
- Considering this is a "developer" mode, I skipped cleanup (removing RPMs) in manageiq-base and only added cleanup to manageiq-ui-worker, to avoid having duplicate code in …
=> Support for local RPMs

images/manageiq-orchestrator/container-assets/entrypoint, manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/helpers/miq-components/orchestrator.go
When provided, we will create a group with the given name with
the super administrator role. The main use case would be when
a user wants to deploy with basic auth totally disabled as soon
as the application comes up. This means that they need at least one
group in the application that matches a group in their identity
provider.
We also now run a full seed after migrating the database on initial
deploy so that we can create the initial group correctly.
Fixes #508
=> Add a CR parameter for an initial group name

images/manageiq-ui-worker/Dockerfile, images/manageiq-webserver-worker/Dockerfile, manageiq-operator/pkg/helpers/miq-components/httpd_conf.go, templates/app/httpd.yaml
Fixes #516
After making this change, assets were not accessible on the SUI login page. This is because the API doesn't have access to asset paths as they are not compiled for that image. The problematic code is https://github.com/ManageIQ/manageiq-api/blob/7776a631894bc71438c46a5c14d649432e93f52b/app/controllers/api/api_controller.rb#L95-L102
I think it would be easier to wait for RPM-based builds than to make and test the changes needed to get asset compilation into the API image.
@simaishi I'm not sure what the granularity is for the rpms, will there be a single package for the assets or will it be more complicated than that?
=> Prevent API calls from going to the UI worker

bin/build
If the build_arg is not consumed, then you get the following warning:
[Warning] One or more build-args [RPM_PREFIX] were not consumed
However, the builds succeed, so it's not a problem. This will make the
bin/build simpler and less prone to error if and when the actual image
Dockerfiles change.
See https://github.com/ManageIQ/manageiq-pods/pull/519#issuecomment-637609255
@carbonin @simaishi Please review.
=> Pass RPM_PREFIX to all images

images/manageiq-ui-worker/container-assets/manageiq-http.conf, manageiq-operator/pkg/helpers/miq-components/httpd_conf.go, templates/app/httpd.yaml
This changes the httpd pod config to push notifications requests
to the ui service instead of the "websocket" service (which actually
doesn't exist anymore).
It also configures the httpd instance in the ui image to handle
websockets in the same way
Fixes #517
=> Move notification handling to the UI worker

manageiq-operator/pkg/helpers/miq-components/httpd_conf.go, templates/app/httpd.yaml
Prior to this change we didn't have a proxy for remote consoles
so there was no way for them to work properly.
Fixes #536
=> Add httpd config for rewriting remote consoles to the correct service

manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/memcached.go
Prior to this change, any changes to the on-cluster CR would not be
reflected in the memcached service and deployment. Additionally
changes to the service and deployment would not be resolved to the
correct state by the operator.
Both of those cases are now handled by this patch.
Applies to #438
The first commit also does some light refactoring of the logger so the naming is easier to understand.
=> Use controllerutil.CreateOrUpdate to maintain memcached resources

images/manageiq-base/Dockerfile
The centos 8.1 repo rpm has been removed now that centos 8.2
has been released
This was causing the builds to fail when trying to install the repos
cc @simaishi
=> Use ubi 8.2 and centos 8.2 in base image

manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml, manageiq-operator/deploy/operator.yaml, manageiq-operator/pkg/helpers/miq-components/httpd.go, manageiq-operator/pkg/helpers/miq-components/kafka.go, manageiq-operator/pkg/helpers/miq-components/memcached.go, manageiq-operator/pkg/helpers/miq-components/postgresql.go
Similar to https://github.com/ManageIQ/manageiq/pull/20279
=> Explicitly set the image pull policy to IfNotPresent

manageiq-operator/README.md, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml, manageiq-operator/deploy/operator.yaml
Pull always since we're using the latest tag which is not static
=> Switch to latest since v0.0.1 tag doesn't exist yet

images/manageiq-base/Dockerfile
A part of https://github.com/ManageIQ/manageiq-appliance-build/issues/422
Requires https://github.com/ManageIQ/manageiq-rpm_build/pull/58 (and new rpm build with this change)
=> Move ovirt-ansible rpm installs to manageiq-gemset requires

manageiq-operator/README.md, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml, manageiq-operator/deploy/operator.yaml
Pull always since we're using the latest tag which is not static
Based on https://github.com/ManageIQ/manageiq-pods/pull/546#issuecomment-645419573
=> [JANSA] Switch to latest-jansa since v0.0.1 tag doesn't exist yet

manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/memcached.go, manageiq-operator/pkg/helpers/miq-components/postgresql.go, manageiq-operator/pkg/helpers/miq-components/util.go
Primarily this PR adds the controller references that were missing from https://github.com/ManageIQ/manageiq-pods/pull/547
In addition it does some minor refactoring by renaming some functions and removing the generic mutate function generating functions in favor of smaller bits of shared logic (in this case around adding the app label).
Fixes #554
=> Add controller reference to PG objects

manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Previously a user was not able to change the actual image name for
the worker images nor were they able to deploy with anything other
than the namespace and tag deployed for the orchestrator.
This gives a bit more flexability in that one image can be replaced
at a time and also allows a user to specify an image ref with a
digest rather than a tag
Should be backported only if https://github.com/ManageIQ/manageiq/pull/20297 is backported.
Fixes #557 
cc @Fryguy
=> Add an override for the worker images deployed by the orchestrator

images/manageiq-base-worker/Dockerfile, images/manageiq-base/Dockerfile, images/manageiq-orchestrator/Dockerfile, images/manageiq-ui-worker/Dockerfile, images/manageiq-webserver-worker/Dockerfile
Requires https://github.com/ManageIQ/manageiq-appliance/pull/289 and https://github.com/ManageIQ/manageiq-rpm_build/pull/73 (and new rpm created with the changes)
Although creating rpm manifest is needed only in manageiq-base and manageiq-orchestrator right now, calling the script in all images, in case we add/remove rpms in other images in the future.
A part of https://github.com/ManageIQ/manageiq-appliance-build/pull/429
=> Generate rpm manifest

manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
- Fixed typo in the description for httpdAuthConfig, referencing OIDCCliencSecret, should be OIDCClientSecret.
/cc @carbonin, minor.
=> Fixed typo in the description for httpdAuthConfig

manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Since we only have one server, it should be static.
Also, prevent the reconcile from generating a new GUID on every run.
Fixes #573
=> Use the CR's UID rather than generating a new one for the orchestrator

manageiq-operator/go.mod, manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/httpd.go, manageiq-operator/pkg/helpers/miq-components/kafka.go, manageiq-operator/pkg/helpers/miq-components/memcached.go, manageiq-operator/pkg/helpers/miq-components/orchestrator.go, manageiq-operator/pkg/helpers/miq-components/postgresql.go, manageiq-operator/pkg/helpers/miq-components/rbac.go, manageiq-operator/pkg/helpers/miq-components/util.go
This PR creates a default service account which will be used by any deployment not already using one we define (the orchestrator and, in some cases, httpd, already use a service account to escalate various privileges). Having done that, we can now associate the image pull secret to all the service accounts we create to ensure it is available to all deployments that are created by either the operator or orchestrator.
I think we may want this in Jansa, so I'll probably have to make a separate PR there as master has diverged rather significantly with the `CreateOrUpdate` changes.
=> Use a service account for pull secrets

manageiq-operator/pkg/helpers/miq-components/httpd.go
The httpd pod is missing the label "service": "httpd" that the service is using as a selector.  So traffic is not getting through to the httpd pods.
=> Fix missing label for selector

manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/httpd.go
- Enhancement to optionally fetch the OIDCAuthIntrospectionURL from the Provider Metadata URL if not provided to us.
Solves: https://github.com/ManageIQ/manageiq-pods/issues/512
=> Enhancement to optionally fetch the OIDCAuthIntrospectionURL

manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/httpd.go
Enhancement to optionally fetch the OIDCAuthIntrospectionURL from the Provider Metadata URL if not provided to us.
Jansa backport of #571
=> [JANSA] Enhancement to optionally fetch the OIDCAuthIntrospectionURL from the Provider

manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
I guess we should default to `jansa-latest` here.  Not sure if we should change to a release tag at some point.  @simaishi @Fryguy @abellotti thoughts?
I noticed this yesterday while smoke testing jansa-1-rc1.
=> [JANSA] We should default to jansa, not master

manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/helpers/miq-components/httpd.go
Fixes https://github.com/ManageIQ/manageiq-pods/issues/605
**Issue Description:**
The code currently uses the Non-standard token introspection endpoint, token_introspection_endpoint.
The standard on is: introspection_endpoint
Fixes https://github.com/ManageIQ/manageiq-pods/issues/605
@miq-bot add-label bug
=> Use standard token introspection endpoint

manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
Follow up for https://github.com/ManageIQ/manageiq-pods/pull/582 (backport of https://github.com/ManageIQ/manageiq-pods/pull/571) - looks like that PR added description to wrong variables.
=> [JANSA] Fix oidcAuthIntrospectionURL/oidcClientSecret description

images/miq-app/Dockerfile
We never added qpid-proton to ivanchuk podified builds. But now [STF Event monitor is added to OpenStack](https://github.com/ManageIQ/manageiq-providers-openstack/pull/556) and that requires qpid-proton. Without bundling with qpid-proton, the app fails to start.
Since we're adding the gem, I'm adding 2 extra packages that go with qpid-proton for Nuage provider as well.
=> [IVANCHUK] Bundle with qpid-proton

manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
Do not bring up:
- the PostgreSQL service if the user is using their own external PostgreSQL server and
they specified the postgresql secret with the external PostgreSQL hostname defined there. 
- the Kafka and Zookeeper service if the user specified a Kafka secret with a Kafka messaging
service hostname defined.
Fixes: https://github.com/ManageIQ/manageiq-pods/issues/529
=> Do not bring up the PostgreSQL or Kafka/Zookeeper services if specifying external services

manageiq-operator/README.md
This PR enhances the README to include a description for configuring OIDC with a CA Certificate.
It is beyond the scope of this PR to describe how to get the CA secret.
@bdunne Here we go again 😄 Please review
=> Add instructions for Configuring OpenID-Connect with a CA Certificate

manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
Fixes https://github.com/ManageIQ/manageiq/issues/20511
This PR helps to ensure OIDC Cache is not undersized for most installations by increasing OIDCCacheShmEntrySizeMax from the default of 16913 bytes to 65536.
=> Add OIDCCacheShmEntrySizeMax parameter

README.md
Update README for rpm build related bin/build options:
`-b` build rpms locally before building images
`-l` build images using existing local rpms
`-s` build images using latest tagged rpms only, excluding nightly build
Also removed ENV variables no longer in use.
=> Update README for building images with rpm build options

bin/build
Since operator-sdk is needed, not everyone may have that, but still could build the other images.  This gives a way to skip building operator images
@simaishi Please review.
=> Add ability to skip operator build

manageiq-operator/pkg/helpers/miq-components/kafka.go, manageiq-operator/pkg/helpers/miq-components/postgresql.go, manageiq-operator/pkg/helpers/miq-components/util.go
Adding the backup annotations tells velero that it should create a backup of the listed volumes.
https://blog.kubernauts.io/backup-and-restore-of-kubernetes-applications-using-heptios-velero-with-restic-and-rook-ceph-as-2e8df15b1487
```
oc describe pod/postgresql-6cdcdc5d9d-jml9m
Name:           postgresql-6cdcdc5d9d-jml9m
Namespace:      bdunne-miq
Priority:       0
Node:           <redacted>
Start Time:     Thu, 10 Sep 2020 21:13:31 -0400
Labels:         app=manageiq
name=postgresql
pod-template-hash=2787871858
Annotations:    backup.velero.io/backup-volumes: miq-pgdb-volume
openshift.io/scc: restricted
....
```
=> Add backup annotations for velero

images/manageiq-base/Dockerfile
The Jansa podified build is hitting the same error as described in https://github.com/ManageIQ/manageiq-appliance-build/pull/440 for ansible venv setup.  That PR didn't fix the issue for podified, as podified build doesn't run post actions in the same order as appliance build:
ovirt_ansible -> python_modules (appliance)
python_modules -> ovirt_ansible (podified)
ovirt_ansible is what installs the needed package.
This is not an issue in master branch, as ovirt related packages were moved to rpm "Requires" and packages are no longer being installed as a post action. So I'm going to just swap the order for jansa podified build to match appliance build, which will eliminate the error.
=> [JANSA] Install ovirt packages before ansible venv packages

manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml
The ManageIQ operator was missing an entry for `provider:`, causing it to show as `provider by [object Object]` under "Installed Operators" in the OCP console.
/cc @bdunne @abellotti
=> Add ManageIQ as the provider of the upstream operator

manageiq-operator/README.md, manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/app-secret.go, manageiq-operator/pkg/helpers/miq-components/cr.go, manageiq-operator/pkg/helpers/miq-components/httpd.go, manageiq-operator/pkg/helpers/miq-components/kafka.go, manageiq-operator/pkg/helpers/miq-components/operator.go, manageiq-operator/pkg/helpers/miq-components/postgresql.go, manageiq-operator/pkg/helpers/miq-components/rbac.go, manageiq-operator/pkg/helpers/miq-components/util.go
Depends On:
This allows us to simplify the listing the resources that need backing up.
`velero backup create my_backup_name -l velero-backup=t`
WIP because I need to add some logic to ensure that the label exists on some objects that we expect the deployer to create, but I wanted to consolidate the label naming discussion here.
Naming:
- Start the label name with something like `miq-` or `manageiq.org/` causes some problems for productization.
- Other apps in our namespace could use the same label if it's not namespaced.
Items that need to be backed up:
- Secrets from keys in the CR:
- PVCs:
- Other objects:
=> Add velero-backup label to important resources that need to be backed up

manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
Caused `"error":"an empty namespace may not be set during creation"` because the secret didn't exist and `CreateOrUpdate` was trying to create it.
=> Skip reconciling the OIDC Client Secret if one isn't specified

images/manageiq-base/Dockerfile
Podified build is now failing because RHEL 8.3 came out yesterday and some packages conflict with CentOS 8.2.
```
Error:
Problem 1: package dracut-network-049-70.git20200228.el8.x86_64 requires dracut = 049-70.git20200228.el8, but none of the providers can be installed
- cannot install both dracut-049-95.git20200804.el8.x86_64 and dracut-049-70.git20200228.el8.x86_64
- cannot install the best update candidate for package dracut-network-049-70.git20200228.el8.x86_64
- cannot install the best update candidate for package dracut-049-70.git20200228.el8.x86_64
Problem 2: package e2fsprogs-libs-1.45.4-3.el8.x86_64 requires libcom_err(x86-64) = 1.45.4-3.el8, but none of the providers can be installed
- cannot install both libcom_err-1.45.6-1.el8.x86_64 and libcom_err-1.45.4-3.el8.x86_64
- cannot …
```
=> Exclude RHEL 8.3 packages that conflict with CentOS 8.2

manageiq-operator/pkg/helpers/miq-components/httpd.go, manageiq-operator/pkg/helpers/miq-components/kafka.go, manageiq-operator/pkg/helpers/miq-components/memcached.go, manageiq-operator/pkg/helpers/miq-components/orchestrator.go, manageiq-operator/pkg/helpers/miq-components/postgresql.go
Rolling deployments require that a new pod be available before the old pod is killed for availability reasons.  However we have many services that should only ever have a single replica and having a second pod can actually cause some strange bugs.  This went unnoticed for many of our services since nothing would prevent a second pod from coming up, but it was found on the postgresql deployment since it needs to mount the data PVC and with most backing storages are `ReadWriteOnce` and the pod can not mount the PVC if another pod has it mounted.
I switched postgresql, kafka, zookeeper, memcached and the orchestrator to `Recreate` since there should only ever be one replica of those.  ~~I didn't see a problem with having multiple replicas of httpd, so I left that as `Rolling`.~~
EDIT: I …
=> Prefer recreate as the deployment strategy for many services.

manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/cr.go, manageiq-operator/pkg/helpers/miq-components/orchestrator.go
In kasparov the source of truth for the server GUID was moved to the CR, but we didn't have a way to migrate the existing value to the CR.  Now, if the CR value is empty, we first look for an existing orchestrator pod and if found, we pull the GUID from the ENV var there, otherwise we generate a new one.  As before, if a value is specified in the CR, that value is used.
=> Attempt to pull server GUID from existing orchestrator if one exists

manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/network_policies.go
Fixes #590 
Allow the following ingress:
- default deny all
- external traffic -> httpd
- httpd -> api
- httpd -> ui
- orchestrator & orchestrated-by -> postgres
- orchestrator & orchestrated-by -> memcached
TODO:
=> Add Ingress Network Policies to the operator

manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml, manageiq-operator/deploy/role.yaml
Apparently I missed this in #649 
Caused:
```
{"level":"info","ts":1607019695.5361571,"logger":"cmd","msg":"Operator Version: 0.0.1"}
{"level":"info","ts":1607019695.5362833,"logger":"cmd","msg":"Go Version: go1.15.1"}
{"level":"info","ts":1607019695.536313,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1607019695.53633,"logger":"cmd","msg":"Version of operator-sdk: v0.15.1"}
{"level":"info","ts":1607019695.5367808,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1607019696.4477308,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1607019696.4512756,"logger":"leader","msg":"Became the leader."}
{"level":"info","ts":1607019697.2886543,"logger":"controller-runtime.metrics","msg":"metrics server is starting to …
```
=> Add permissions to our role for Network Policies

manageiq-operator/pkg/helpers/miq-components/httpd.go, manageiq-operator/pkg/helpers/tlstools/generate_crt.go
This is still a self-signed certificate, but now at least it matches the name on the ingress route.
=> Set the TLS certificate CN to the application domain

manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
This should help with debugging when something unexpected blows up during reconcile.  Unfortunately there is only `Info` or `Error`, no `Debug` or anything else.  https://godoc.org/github.com/go-logr/logr#Logger
After:
```
$ operator-sdk run --local --namespace=bdunne-miq
INFO[0000] Running the operator locally in namespace bdunne-miq. 
{"level":"info","ts":1607556770.8386567,"logger":"cmd","msg":"Operator Version: 0.0.1"}
{"level":"info","ts":1607556770.838682,"logger":"cmd","msg":"Go Version: go1.14.4"}
{"level":"info","ts":1607556770.8386874,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1607556770.8386927,"logger":"cmd","msg":"Version of operator-sdk: v0.15.1"}
{"level":"info","ts":1607556770.8412135,"logger":"leader","msg":"Trying to become the leader."} …
```
=> Add debug logging for the reconcile loop

images/manageiq-base/Dockerfile
UBI 8.3 image was updated yesterday and that is causing build to fail:
```
Problem 1: package net-snmp-utils-1:5.8-17.el8.x86_64 requires net-snmp-libs(x86-64) = 1:5.8-17.el8, but none of the providers can be installed
- cannot install both net-snmp-libs-1:5.8-18.el8_3.1.x86_64 and net-snmp-libs-1:5.8-17.el8.x86_64
- cannot install the best update candidate for package net-snmp-utils-1:5.8-17.el8.x86_64
- cannot install the best update candidate for package net-snmp-libs-1:5.8-17.el8.x86_64
...
```
Reported by @jrafanie
=> Exclude net-snmp* packages from ubi repo

.gitignore, README.md, images/manageiq-base-worker/Dockerfile, images/manageiq-base-worker/container-assets/extract-vmware-vddk, images/manageiq-base-worker/container-assets/install-vmware-vddk
Fixes: https://github.com/ManageIQ/manageiq-pods/issues/538
I'm not sure if we want to go this route or have a dedicated `Dockerfile` that builds on top of the worker base image, but since it's used for both scanning and webmks, I thought this might be easier.  Either way, the code would be the same.
=> Add simple installation process for the VMware VDDK

images/miq-app/Dockerfile
The latest version of bundler (2.2.4) doesn't work with the version of git available on CentOS 7. It's probably not a good idea to keep updating bundler on older branches anyway, so locking to 2.1.4 which is what was used in ivanchuk-7 release.
=> [IVANCHUK] Lock bundler to v2.1.4

bin/build
Without `--pull` option, the base image specified in manageiq-operator Dockerfile (registry.access.redhat.com/ubi8/ubi-minimal:latest) doesn't get updated even if there is a newer version available.
=> Pull the latest base image for operator build

manageiq-operator/README.md, manageiq-operator/pkg/helpers/miq-components/cr.go
If a secret by the name of `image-pull-secret` exists, set that in the CR and attempt to use it.
=> Attempt to default the image pull secret

manageiq-operator/pkg/helpers/miq-components/network_policies.go
Only applies to pods labeled with the AppName defined in the CR
=> Limit the scope of the default-deny network policy

manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/helpers/miq-components/cr.go, manageiq-operator/pkg/helpers/miq-components/httpd.go, manageiq-operator/pkg/helpers/miq-components/kafka.go, manageiq-operator/pkg/helpers/miq-components/memcached.go, manageiq-operator/pkg/helpers/miq-components/orchestrator.go, manageiq-operator/pkg/helpers/miq-components/postgresql.go
Adding support for optional Image References instead of the ImageName and ImageTag parameter pairs. If not specified,
then the default ImageName:ImageTag image reference is used.
New optional CR parameters:
- PostgresqlImage
- HttpdImage
- OrchestratorImage
- MemcachedImage
- KafkaImage
- ZookeeperImage
Todo:
=> Adding support for optional Image References

manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/cr.go, manageiq-operator/pkg/helpers/miq-components/httpd.go
- Move enforcement to the CRD OpenAPI schema
- Move privileged checking in the CR into the httpdImage function since there is no more error case
- Clean up unnecessary error checking
Based on https://github.com/ManageIQ/manageiq-pods/pull/680#discussion_r574648175
=> Only allow valid authentication types in the CRs

images/manageiq-base/Dockerfile
dracut was updated in UBI8 repo recently, and now it's causing a conflict with what's in CentOS.
```
Error:
Problem: package dracut-network-049-95.git20200804.el8.x86_64 requires dracut = 049-95.git20200804.el8, but none of the providers can be installed
- cannot install both dracut-049-95.git20200804.el8_3.4.x86_64 and dracut-049-95.git20200804.el8.x86_64
- cannot install the best update candidate for package dracut-network-049-95.git20200804.el8.x86_64
- cannot install the best update candidate for package dracut-049-95.git20200804.el8.x86_64
```
dracut (and net-snmp) seems to cause conflicts often, this should probably be kept excluded all the time.
=> Exclude dracut from ubi8 repo to avoid conflicts

images/manageiq-base-worker/container-assets/manageiq_liveness_check
7d841daecccaacbbe made this work but container_env does expensive URL
escaping of the DATABASE_USER and PASSWORD to build DATABASE_URL which
is not needed in the liveness check. Since all pods run this liveness check
many times per minutes, it has to be as fast as possible.
This drops a few 100ms from the liveness check depending on the environment.
=> We only need the ruby environment, not full container_env

images/manageiq-base-worker/container-assets/manageiq_liveness_check
Replace [heartbeat_check.rb and friends](https://github.com/ManageIQ/manageiq/blob/c43b2093199bb6942318c3102371b79c03f95473/lib/workers/bin/heartbeat_check.rb) with a simple shell script that assumes the heartbeat file now contains a timeout in unix time seconds since epoch.
Depends on the core change to write these files in unix time. 
Preliminary results:
kasparov-1 environment running mostly idle
```
$ oc adm top pods
NAME                                 CPU(cores)   MEMORY(bytes)
1-event-handler-5dd956d75f-fr25h     74m          227Mi
1-generic-5865997d56-2xzrt           54m          322Mi
1-generic-5865997d56-fzwvz           72m          348Mi
1-priority-576657869b-9r4qf          71m          317Mi
1-priority-576657869b-swgdp          61m          297Mi …
```
=> Fasterer liveness check

manageiq-operator/cmd/manager/main.go
Honor the Pod's environment variable OPERATOR_NAME when choosing the lock name for the operator.
=> Honor the Env's OPERATOR_NAME when determining the operator lock name.

manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/httpd.go, manageiq-operator/pkg/helpers/miq-components/util.go
Added Support for Managed OIDC Configurations.
With Managed OIDC configurations, parent managing applications, can rewire and reconfigure all OIDC client registrations against an identity provider, then provide us the updated parameters via the HttpdAuthConfig secret.
With this PR, the operator would define the following httpd pod environment variable:
- MANAGED_HTTPD_CFG_VERSION
to reflect the latest resourceVersion of the provided HttpdAuthConfig secret. 
Upon an update to the secret, the Httpd pod environment will get updated and then restarted by Openshift for Apache to honor the new configuration.
<strike>Added support for Managed OIDC Configurations.
Managed environments provide the configured OIDC parameters as secret key/value pairs in the HttpdAuthConfig secret
as follows:
- …
=> Added support for Managed OIDC Configurations

bin/build
Without this PR, the operator dir is not relativel to the base dir, and is assuming that `pwd` is the base dir, so when it tries to pushd to it, it fails
Note that this PR changes the meaning of `-d`, so it is a breaking change and will require changes on the build machine.
=> Ensure images and operator dirs are relative to the base dir

images/manageiq-base-worker/container-assets/extract-vmware-vddk
```
STEP 9: COPY --from=vddk /vddk/vmware-vix-disklib-distrib /usr/lib/vmware-vix-disklib
Error: error building at STEP "COPY --from=vddk /vddk/vmware-vix-disklib-distrib /usr/lib/vmware-vix-disklib": error adding sources [/var/lib/containers/storage/overlay/053d288f78f5120912955cb2f0a356d21a9ddf7561674fe2b1826eca82b4edcd/merged/vddk/vmware-vix-disklib-distrib]: no items matching glob "/var/lib/containers/storage/overlay/053d288f78f5120912955cb2f0a356d21a9ddf7561674fe2b1826eca82b4edcd/merged/vddk/vmware-vix-disklib-distrib" copied (1 filtered out): no such file or directory
```
=> Newer versions of podman won't copy from an empty directory

manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/httpd.go
Otherwise it will not be there for a restore and will cause problems deploying the httpd pod
=> If there is a HttpdAuthConfig, add the backup label to it

manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
The httpd-init container is failing with
```
h-4.4# systemctl status httpd
● httpd.service - The Apache HTTP Server
Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
Drop-In: /etc/systemd/system/httpd.service.d
└─environment.conf
Active: failed (Result: exit-code) since Tue 2021-03-09 11:13:42 UTC; 33s ago
Docs: man:httpd.service(8)
Process: 58 ExecStart=/usr/sbin/httpd $OPTIONS -DFOREGROUND (code=exited, status=1/FAILURE)
Main PID: 58 (code=exited, status=1/FAILURE)
Mar 09 11:13:42 httpd-5696d5d749-d6s9k systemd[1]: Starting The Apache HTTP Server...
Mar 09 11:13:42 httpd-5696d5d749-d6s9k httpd[58]: httpd: Syntax error on line 356 of /etc/httpd/conf/httpd.conf: Syntax error on line 6 of /etc/httpd/conf.d/authentication.conf: Cannot load …
```
=> Move from  module mod_auth_kerb to mod_auth_gssapi

images/manageiq-base-worker/Dockerfile, images/manageiq-base/Dockerfile, images/manageiq-orchestrator/Dockerfile, images/manageiq-ui-worker/Dockerfile, images/manageiq-webserver-worker/Dockerfile
These changes cause the base-worker image to drop from 2.2GB to 1.99GB
(~200MB / 9%) and the ui-worker image to drop from 2.51GB to 2.18GB
(~330MB / 13%).
Notable savings are:
- When running the generate_rpm_manifest, the dnf commands fill the
cache, which wasn't being cleaned. This particulary affects the
manifest run immediately after installing manageiq-ui dropping that
layer size from 123MB to 6.6MB.
- When installing the pythin dependencies, we run dnf install, which
wasn't being cleaned. This layer dropped from 604MB to 435MB
- The chgrp commands are done in a separate layer from the layer that
installs those files, causing an extra 39MB layer which is
unnecessary.
=> Clear caches better for smaller images

manageiq-operator/build/Dockerfile
Addresses these failures -
- non_inherited_base_label_name,
- non_inherited_base_label_vendor, 
- non_inherited_base_label_description, 
- non_inherited_base_label_summary
=> Added labels to image build to address red hat certification failures on application image

images/manageiq-base/Dockerfile
`appliance_build` stage version doesn't matter, just keep it up to date.  Unfortunately ubi-minimal:latest doesn't include tar, so we can't use it there.
=> Update base image to UBI 8.4, change appliance_build stage to latest

images/manageiq-base/Dockerfile
Previously this was pulling some perl packages from CentOS and others from UBI8 and causing dependency conflicts and not allowing dnf to resolve packages properly.
```
[root@597e0f592269 /]# dnf update
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Last metadata expiration check: 0:30:34 ago on Thu 03 Jun 2021 09:05:34 PM UTC.
Error:
Problem 1: package perl-threads-1:2.21-2.el8.x86_64 requires libperl.so.5.26()(64bit), but none of the providers can be installed
- cannot install both perl-libs-4:5.30.1-451.module+el8.3.0+6961+31ca2e7a.x86_64 and perl-libs-4:5.26.3-419.el8.x86_64
- cannot install …
```
=> Prefer Perl from the CentOS appstream rather than UBI 8 appstream

manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
these are behind ssl and should not be cached
@miq-bot add-label bug
=> no longer cache oidc_login pages

images/manageiq-ui-worker/container-assets/manageiq-http.conf
LimitRequestFieldSize: Expand this to a large number to allow pass-through.
This does not introduce a potential DoS, because the value is validated by
the httpd container first.  However, if a user changes this value in the
httpd container, we need to be able to accomodate that value here also.
512K was chosen as the size because that is also the maximum limit of
the OIDCCacheShmEntrySizeMax value for OIDC.
@bdunne Please review.
=> Expand LimitRequestFieldSize in the internal httpd

manageiq-operator/pkg/helpers/miq-components/cr.go, manageiq-operator/pkg/helpers/miq-components/orchestrator.go, manageiq-operator/pkg/helpers/miq-components/postgresql.go
For consistency, move this logic into cr.go and rename it to match the CR parameter name.
=> Replace postgresqlSecretName default value logic in cr.go like others

manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
See default secret value here: https://github.com/ManageIQ/manageiq-pods/blob/master/manageiq-operator/pkg/helpers/miq-components/postgresql.go#L22
=> Default internal hostname is "postgresql", not blank

manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/postgresql.go
Ensure that the postgresql secret (whether created by the operator or installer) is managed by the operator with backup and app labels added and controller reference set.
Built on top of #732
=> Fix postgresql secret labeling

manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml, manageiq-operator/deploy/olm-catalog/manageiq-operator/manifests/manageiq.org_manageiqs_crd.yaml, manageiq-operator/go.sum, manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go, manageiq-operator/pkg/apis/manageiq/v1alpha1/zz_generated.deepcopy.go, manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/cr_migration/20210503163000_initial_migration.go, manageiq-operator/pkg/helpers/cr_migration/20210504113000_migrate_image_names.go, manageiq-operator/pkg/helpers/cr_migration/cr_migration.go, manageiq-operator/pkg/helpers/miq-components/cr.go, manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Based on discussions in https://github.com/ManageIQ/manageiq-pods/issues/676
Notes: (not sure if these should be handled here or in a followup)
- Currently uses the CR object, not unstructured JSON
- `MigrationsRan` are currently stored in `Spec` rather than `Status`, for some reason I couldn't get that working.
=> Initial pass at CR migrations

images/manageiq-base/Dockerfile
We were not pulling in the latest nightly RPMs due to a bug in `manageiq-release 14.0-1`
=> Update manageiq-release RPM version

manageiq-operator/pkg/helpers/miq-components/application.go, manageiq-operator/pkg/helpers/miq-components/httpd.go, manageiq-operator/pkg/helpers/miq-components/httpd_conf.go, manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Part of: https://github.com/ManageIQ/manageiq-pods/issues/724
Depends on: https://github.com/ManageIQ/manageiq/pull/21527
~~WIP because I want to do a little bit more testing once https://github.com/ManageIQ/manageiq/pull/21527 is merged~~
=> Enable SSL on the API and UI pods when certificates exist

.gitignore, tools/cert_generator.rb
Based on discussion in https://github.com/ManageIQ/manageiq-documentation/pull/1574#discussion_r746073542
=> Add a tool for generating certificates to enable SSL/TLS between pods

images/manageiq-base/Dockerfile, images/manageiq-webserver-worker/Dockerfile
- We don't use it
- It's also causing conflicts
```
Error:
Problem 1: cannot install the best update candidate for package python3-subscription-manager-rhsm-1.28.13-4.el8_4.x86_64
- nothing provides python3-cloud-what = 1.28.21-3.el8 needed by python3-subscription-manager-rhsm-1.28.21-3.el8.x86_64
Problem 2: package python3-subscription-manager-rhsm-1.28.13-4.el8_4.x86_64 requires subscription-manager-rhsm-certificates = 1.28.13-4.el8_4, but none of the providers can be installed
- cannot install both subscription-manager-rhsm-certificates-1.28.21-3.el8.x86_64 and subscription-manager-rhsm-certificates-1.28.13-4.el8_4.x86_64
- problem with installed package python3-subscription-manager-rhsm-1.28.13-4.el8_4.x86_64
- cannot install the best update candidate for package …
```
=> Remove subscription-manager

images/manageiq-base/Dockerfile
With the merge of https://github.com/ManageIQ/manageiq-rpm_build/pull/208
and https://github.com/ManageIQ/manageiq-rpm_build/pull/213, there is no
longer a need to pull in the ovirt-release repo.
@bdunne Please review. cc @jrafanie
=> Remove ovirt-release repo

bin/build, lib/tasks/release.rake
Introduced in 40d83bdb5361f0caaa4b96893b240a7e8593a204
Presented as:
```
[1/2] STEP 6/7: ARG GIT_AUTH
--> Using cache 0a3b98757153fa94ceb77db0b738ea8a9332c96b95303bf16fd8bfa411357b5b
--> 0a3b9875715
[1/2] STEP 7/7: RUN mkdir build &&     if [[ -n "$GIT_AUTH" ]]; then GIT_HOST=${GIT_AUTH}@${GIT_HOST}; fi && curl -L https://${GIT_HOST}/${BUILD_ORG}/${CORE_REPO_NAME}-appliance-build/tarball/${BUILD_REF} | tar vxz -C build --strip 1
curl: (3) [globbing] unmatched close brace/bracket in column 68
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
=> [MORPHY] Fix typo

manageiq-operator/pkg/helpers/miq-components/httpd.go
```
{"level":"error","ts":1642705176.2017493,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"manageiq-controller","request":"cp4waiops/im-iminstall","error":"Deployment.apps \"httpd\" is invalid: spec.template.spec.volumes[2].name: Duplicate value: \"user-auth-config\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error
/root/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232 …
```
=> Fix Httpd reconcile

images/manageiq-base/Dockerfile
This should ensure that we get the latest versions sooner.
Copy from https://github.com/ManageIQ/container-httpd/pull/67
=> Pull httpd from UBI (not CentOS) Appstream repo

README.md
The -d option specifies the base_dir, the images_dir is relative to the
base_dir.
When using the commands in the README I get the following error:
```
bin/build -d images -r manageiq -l
bin/build: line 65: pushd: images/images: No such file or directory
```
What works is
```
bin/build -d . -r manageiq -l
```
=> Fix `bin/build -d` in README

manageiq-operator/README.md
The top-level manageiq-pods/README.md includes steps for building custom images based on locally built RPMs which is helpful for verifying code changes that aren't included in a build yet.
The manageiq-operator docs however do not describe what you have to do in order for you to actually deploy these custom images however.
This adds the steps that you need to take in order to test your custom images.
=> Document steps for operator to deploy custom images

images/manageiq-webserver-worker/Dockerfile, manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
Enables: https://github.com/ManageIQ/manageiq/pull/21766
=> Allow httpGet health probes using the /ping endpoint

manageiq-operator/pkg/controller/manageiq/manageiq_controller.go, manageiq-operator/pkg/helpers/miq-components/application.go, manageiq-operator/pkg/helpers/miq-components/httpd_conf.go, manageiq-operator/pkg/helpers/miq-components/network_policies.go, manageiq-operator/pkg/helpers/miq-components/orchestrator.go, tools/cert_generator.rb
Part of: https://github.com/ManageIQ/manageiq-pods/issues/829
Also, allow traffic from httpd to the remote console workers
=> Add HTTPD configs for the remote console worker

images/manageiq-base/Dockerfile
Copy of https://github.com/ManageIQ/container-httpd/pull/74
=> Pull mod_ssl from UBI, not CentOS Appstream

images/manageiq-base/Dockerfile
Copied from: https://github.com/ManageIQ/container-httpd/pull/75
=> Install all httpd dependencies before enabling CentOS repos

images/manageiq-base/Dockerfile
There's a bug in 14.0-1 where some of the repos weren't updated and still point to v13
This is causing container builds to fail
=> [NAJDORF] Use the latest manageiq-release 14.0 RPM

images/manageiq-base/Dockerfile
Red Hat Enterprise Linux 8 repo will be removed if we remove **subscription-manager** on s390x due to which createrepo_c and other packages were failed to install within manageiq-base image.
=> Don't remove subscription-manager on s390x

bin/build
This fixes issues where the images created by podman on s390x are not in v2 image format, which causes issues later when we create multi-arch image manifests.
@miq-bot add-label bug
I think we also have to update the operator-sdk build, but I'm really not sure how.
=> Add format docker for s390x builds using podman

images/manageiq-base/Dockerfile
For https://github.com/ManageIQ/manageiq-ui-classic/issues/8300
NOTE: See https://github.com/ManageIQ/manageiq-ui-classic/issues/8300 for the breakdown of required PRs.
=> Drop nodejs from podified as it's a build dependency now

.github/workflows/ci.yaml
=> Add timeout-minutes to setup-ruby job

bin/build
Locally, this reduces the number of parameters to pass, and defaults
them to the likely values you'd want locally. In build we already pass
these so nothing should change there.
=> Simplify bin/build to default BASE_DIR and REPO

images/manageiq-base-worker/Dockerfile, images/manageiq-base/Dockerfile, images/manageiq-base/container-assets/clean_dnf_rpm, images/manageiq-orchestrator/Dockerfile, images/manageiq-ui-worker/Dockerfile, images/manageiq-webserver-worker/Dockerfile
This change reduces the UI worker image size from 2.063GB to 2.018GB
(44MB, 2.1%)
- Add the removal of dnf logs, dnf history, and rpm __db lock files.
This eliminates roughly 2-6MB per invocation.
- Move the cleaning of dnf and rpm assets into a script, which makes it
easier to use across layers and images.
- Remove redundant rebuild of the rpm manifests, since ther are
unnecessary unless rpm changes are made.
- Collapse the modifications of the httpd package into the same layer as
when it's installed.
Part of #736
EDIT: I forgot to mention this also has significant time savings as well.  Locally, the rpm manifest generation steps can take  ~100s (1m40s) x 5 images = ~500s (8m20s).  After this PR, there are only 2 calls, so that's 200s (3m20s) for a savings of ~5min per build
=> Clean more files after dnf installing

images/manageiq-base/Dockerfile, images/manageiq-webserver-worker/Dockerfile
Depends on
The following weak dependencies will end up not being installed.
```
apr-util-bdb
apr-util-openssl
geolite2-city
geolite2-country
libmaxminddb
perl-Digest
perl-Digest-MD5
perl-IO-Socket-IP
perl-IO-Socket-SSL
perl-libnet
perl-Mozilla-CA
perl-Net-SSLeay
perl-URI
python38-pip
python3-jmespath
rubygem-bundler
rubygem-json
rubygem-rdoc
```
This drops the image size roughly from 2.063GB to 1.943GB (120MB, 5.85%).  Of note, the geolite2 packages are somewhat large, so part of #736 
---
Packages sizes sorted by size:
```
56549434  geolite2-city
7784945  python38-pip
3424334  geolite2-country
1714611  rubygem-rdoc
1359290  rubygem-bundler
1325271  perl-Net-SSLeay
618705  perl-IO-Socket-SSL
277135  perl-libnet
216452  perl-URI
119891  python3-jmespath
99525  perl-IO-Socket-IP
97777 …
```
=> Avoid installing weak dependencies 

manageiq-operator/config/manager/manager.yaml
It was used for leader election lock naming in older versions of the operator-sdk.
Dropped by https://github.com/ManageIQ/manageiq-pods/pull/831/files#diff-963be88783f1e1465a03f13199442714132415353ddb038a0f52f6442dde70ceL87-L97
=> OPERATOR_NAME is no longer used

manageiq-operator/config/rbac/role.yaml, manageiq-operator/controllers/manageiq_controller.go, spec/manageiq-operator/crd_spec.rb
- Single quotes are not YAML dumped correctly, use double quotes instead
- Prevent role explosion by listing them all on the same line
The only remaining issues with `make manifests` are:
- It adds creationTimestamp: null
- It tries to add a namespace
- It changes the role name
=> Fix core apigroup definition issues

bin/build, manageiq-operator/Makefile
- After upgrading to operator-sdk 1.x we use make, not operator-sdk to build the operator image
- Also move options to Makefile
Fixes: `must run command in project root dir: project structure requires build/Dockerfile`
=> Rely on make docker-build for consistency

manageiq-operator/go.mod, manageiq-operator/go.sum
Setting `exclude github.com/gogo/protobuf v1.3.1` dowwngrades the package to v1.2.2
najdorf PR: https://github.com/ManageIQ/manageiq-pods/pull/868
=> Fix CVE 2021-3121

images/manageiq-base/container-assets/container_env
When running the docker images directly with something like
`docker run --entrypoint /bin/bash ...`, the values in container_env end
up creating an invalid DATABASE_URL. For diagnostic purposes where you
might want to run Rails console, but don't need the database, this
invalid DATABASE_URL prevents it from starting.
The changes here ensure a valid DATABASE_URL is created allowing usage
of Rails console even if the actual database cannot be connected to.
@jrafanie Please review.
Before:
```
$ docker bash manageiq/manageiq-ui-worker:latest-najdorf
$$ vmdb
$$ source container_env
$$ echo $DATABASE_URL
postgresql://:@:/?encoding=utf8&pool=5&wait_timeout=5&sslmode=prefer
$$ bin/rails c
/usr/share/ruby/irb/completion.rb:18: warning: already initialized constant …
```
=> Add sensible defaults for DATABASE_URL when env vars do not exist

images/manageiq-base/container-assets/container_env
This PR simplifies the creation of the DATABASE_URL by only shelling out to Ruby once instead of twice to build the userinfo.
Using the script from https://github.com/ManageIQ/manageiq-pods/issues/695 for timing, this eliminates one of the Ruby runs, dropping the time (for those 2 calls) from ~0.06s to 0.03s
=> Simplify DATABASE_URL generation

images/manageiq-base/container-assets/container_env
Built on #871 
When certs are not present, `time source container_env` drops from
0m0.266s to 0m0.011s
Closes https://github.com/ManageIQ/manageiq-pods/issues/695
@jrafanie Please review
=> Check for the presence of the certs before calling update-ca-trust

manageiq-operator/api/v1alpha1/helpers/miq-components/operator.go
This will apply the default-deny network policy to the operator pod
Before:
$ curl http://ip_of_operator_pod:8080/abc
404 page not found
After:
$ curl http://ip_of_operator_pod:8080/abc
no response
=> Add app label to the operator pod

manageiq-operator/Dockerfile
The labels were not copied over when the new Dockerfile was generated
=> Add back labels from before the operator-sdk upgrade

bin/build, manageiq-operator/Makefile
If both podman and docker executables are installed (GHA ubuntu-latest), we were adding `--format docker` and sending it to docker which is a problem since that's not an option on Docker.
=>  Use podman if available, fall back to docker 

manageiq-operator/api/v1alpha1/helpers/miq-components/kafka.go
- incorrectly retrieving database secret key instead of kafka secret key hence default kafka secret was not being created
```
Warning  Failed                  3h41m (x12 over 3h43m)    kubelet                  Error: secret "kafka-secrets" not found
```
Ref:
- https://github.com/ManageIQ/manageiq/issues/22132
@miq-bot add_label bug
@miq-bot add_reviewer @agrare, @Fryguy
=> Fix default Kafka secret

manageiq-operator/api/v1alpha1/helpers/miq-components/network_policies.go, manageiq-operator/controllers/manageiq_controller.go
- this network policy is required in order to allow the kafka and zookeeper pods to communicate
```
[2022-09-28 20:38:56,491] INFO Initiating client connection, connectString=zookeeper:2181 sessionTimeout=18000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@1d470d0 (org.apache.zookeeper.ZooKeeper)
[2022-09-28 20:38:56,496] INFO jute.maxbuffer value is 4194304 Bytes (org.apache.zookeeper.ClientCnxnSocket)
[2022-09-28 20:38:56,502] INFO zookeeper.request.timeout value is 0. feature enabled=false (org.apache.zookeeper.ClientCnxn)
[2022-09-28 20:38:56,504] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2022-09-28 20:38:56,514] INFO Opening socket connection to server zookeeper/172.30.71.190:2181. …
```
=> Add Zookeeper network policy

manageiq-operator/Dockerfile
UBI9 requires Power9 or above and Z14 or above.
I don't think we want to force users to upgrade hardware at this time.
=> Revert back to UBI8 for now.

README.md, bin/build, images/manageiq-base/Dockerfile
Updated/Rebased version of #636 
manageiq-appliance-build repo.
With this change, everything is built in manageiq-rpm_build, and no need for source customization in pods, which obsoletes CORE_REPO_NAME, GIT_AUTH and GIT_HOST.
=> Remove manageiq-appliance-build clone and customization hook

images/manageiq-base/Dockerfile
Red Hat removed the sticky bit from /tmp, which causes Dir.tmpdir to fail to find a temp dir.
See https://bugzilla.redhat.com/show_bug.cgi?id=2138434
=> Force the sticky bit on /tmp

manageiq-operator/api/v1alpha1/helpers/miq-components/kafka.go
- added missing probing checks for Kafka to bring it in line with other services
Ref:
- https://github.com/ManageIQ/manageiq/issues/22132
@miq-bot assign @Fryguy 
@miq-bot add_reviewer @agrare
=> Readiness and Liveness probes for Kafka

images/manageiq-base/container-assets/create_local_yum_repo.sh
Sometimes the build fails, but we don't know what is in the local RPM directory.
=> Inspect the content of the local rpms directory to debug build issues

images/manageiq-base/Dockerfile
This is used in the monolithic image when it installs postgresql-server. I thought it was better to enable it here in case we need any dependencies.
This was causing the oparin-1 container build to fail since the monolithic image is built at the same time.
Part of: https://github.com/ManageIQ/manageiq-appliance-build/pull/532
=> Enable postgresql 13 module

manageiq-operator/api/v1alpha1/helpers/miq-components/app-secret.go
This bug was introduced during the operator-sdk upgrade when changing from a create only to a create or update that could be called during reconcile. I was looking up the secret using the wrong name (probably a copy/paste error).
=> Ensure that ManageAppSecret is managing the app secret

images/manageiq-base-worker/container-assets/entrypoint, images/manageiq-base/container-assets/container_env, images/manageiq-orchestrator/container-assets/entrypoint, manageiq-operator/api/v1alpha1/helpers/miq-components/app-secret.go, manageiq-operator/api/v1alpha1/helpers/miq-components/orchestrator.go, manageiq-operator/api/v1alpha1/helpers/miq-components/postgresql.go
Having secrets in ENV vars may be less secure than having files on the filesystem.  Move sensitive information into files.
Depends on:
=> Read secrets from an ENV file if mounted

manageiq-operator/api/v1alpha1/helpers/miq-components/kafka.go, manageiq-operator/api/v1alpha1/helpers/miq-components/network_policies.go, manageiq-operator/controllers/manageiq_controller.go
- added network policy to allow ingress to Kafka pod from orchestrator and worker pods
- set advertised listener in config, this will allow pods to communicate with the Kafka broker
Needed for:
- https://github.com/ManageIQ/manageiq-pods/pull/896
Ref:
- https://github.com/ManageIQ/manageiq/issues/22225
@miq-bot add_reviewer @Fryguy 
=> Allow Kafka communications

.github/workflows/ci.yaml, manageiq-operator/api/v1alpha1/groupversion_info.go, manageiq-operator/go.mod
=> Upgrade Go

.github/workflows/ci.yaml, manageiq-operator/Dockerfile
Followup to #914 
Error:
```
[1/2] STEP 9/9: RUN CGO_ENABLED=0 go build -a -o manager main.go # k8s.io/kube-openapi/pkg/cached
/go/pkg/mod/k8s.io/kube-openapi@v0.0.0-20230308215209-15aac26d736a/pkg/cached/cache.go:242:16: undefined: atomic.Pointer # go.uber.org/multierr
/go/pkg/mod/go.uber.org/multierr@v1.10.0/error.go:224:20: undefined: atomic.Bool note: module requires Go 1.19
Error: error building at STEP "RUN CGO_ENABLED=0 go build -a -o manager main.go": error while running runtime: exit status 2 make: *** [Makefile:142: docker-build] Error 2
```
=> Fix go 1.20 build issues

images/manageiq-base/Dockerfile
- Update CentOS release packages
- `dnf update` system packages to allow for newer packages to be installed (samba-*) later in the dockerfile
=> Ensure latest samba is installed

manageiq-operator/api/v1alpha1/helpers/miq-components/cr.go
Currently we allocate 1GB by default for our Kafka volume however, also by default Kafka creates 50 partitions for consumer offsets which are around 20MB each... which means that we don't have much disk space leftover for additional topics. 
For example on a fresh deployment of Kafka:
```
nasarkhan@Nasars-MacBook-Pro manageiq-operator %  oc exec kafka-584b6d69f6-x9bj2    -- df -ah
Filesystem                                                                                                                                               Size  Used Avail Use% Mounted on
172.30.143.197:6789,172.30.118.45:6789,172.30.81.85:6789:/volumes/csi/csi-vol-828e3e63-a8af-11ed-89ce-0a580afe1005/8a1f0cf2-2e69-47a8-bf8a-033b36665407  1.0G 1000M   24M  98% /bitnami/kafka
```
``` …
```
=> Upsize default Kafka volume capacity

images/manageiq-base/Dockerfile
httpd will still come from the UBI appstream repo due to the exclusion set above.
When the release RPM is swapped, the RPM scripts from that and shadow-utils reset the contents of /etc/passwd causing the apache user to be removed and httpd fails to start due to the missing user.
Based on changes in https://github.com/ManageIQ/manageiq-pods/pull/956
Building with this change I see the package versions that we want:
```
[root@3f6ee3351684 /]# rpm -qa |grep httpd
httpd-2.4.37-51.module+el8.7.0+18499+2e106f0b.5.x86_64
redhat-logos-httpd-84.5-1.el8.noarch
httpd-tools-2.4.37-51.module+el8.7.0+18499+2e106f0b.5.x86_64
httpd-filesystem-2.4.37-51.module+el8.7.0+18499+2e106f0b.5.noarch
[root@3f6ee3351684 /]# rpm -qa |grep samba
samba-common-4.17.5-0.el8.noarch
samba-common-libs-4.17.5-0.el8.x86_64 …
```
=> Install httpd after replacing the release RPM

bin/build, bin/build_hotfix, images/manageiq-hotfix/Dockerfile
- Build on top of existing images by copying over local RPMs and updating only those RPMs (as we would do in a hotfix situation between releases)
- Allow for productized source image names
=> Add a new hotfix image build script

images/manageiq-base/container-assets/create_local_yum_repo.sh
Example:
```
Directory walk started
Directory walk done - 22 packages
Temporary output repo path: /tmp/rpms/.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished
Critical: Cannot rename /tmp/rpms/.repodata/ -> /tmp/rpms/repodata/: Directory not empty
```
=> Fix failure if repodata already exists

images/manageiq-hotfix/Dockerfile
When running a hotfix build, the create_local_yum_repo script might not already have the rm -rf if the image was built before the change was merged
=> Followup to #962

manageiq-operator/api/v1alpha1/helpers/miq-components/postgresql_conf.go
Fixes https://github.com/ManageIQ/container-postgresql/issues/40
Drop the no longer used options for logging to a file.
Related: https://github.com/CrunchyData/postgres-operator/issues/1141#issuecomment-629235277
Technically, it's an enhancement, but you can't look at pg logs in podified without visiting the pg pod so users would probably say this is a bug.
EDIT:  We saw some possibly no longer used/wrong settings so I opened an issue to start that discussion: https://github.com/ManageIQ/manageiq-pods/issues/969
=> Log to stderr by turning off the log file collector

manageiq-operator/api/v1alpha1/manageiq_types.go, manageiq-operator/config/crd/bases/manageiq.org_manageiqs.yaml
All of these should use XImage rather than the combination of: xImage
xImageName (sometimes)
xImageNamespace
xImageTag
=> Mark deprecated spec properties.

manageiq-operator/api/v1alpha1/manageiq_types.go, manageiq-operator/config/crd/bases/manageiq.org_manageiqs.yaml
Backport of #971 
Merge pull request #971 from bdunne/mark_deprecated_spec_properties
Mark deprecated spec properties.
(cherry picked from commit b4934f434ad8bf5c8a20fb377c0fe827a26bed4c)
=> [petrosian] Mark deprecated spec properties.

manageiq-operator/api/v1alpha1/helpers/miq-components/postgresql_conf.go
For posix, the default posix shared memory volume in openshift is 64 MB. We could solve this problem by mounting a larger volume and mounting that.
Or, we can just use sysv with a large enough shmall/shmmax, which we already have.
Since sysv is easier to implement, we're doing this here.
The details below show how to check the shared memory types, sizes, and possible solutions for both posix and sysv.
We originally had posix for dynamic shared memory:
```
postgres=# show shared_buffers;
shared_buffers
----------------
1GB
(1 row)
postgres=# show shared_memory_type;
shared_memory_type
--------------------
mmap
(1 row)
postgres=# show dynamic_shared_memory_type;
dynamic_shared_memory_type
----------------------------
posix
(1 row)
```
with /dev/shm of only the default: 64 MB:
```
sh-4.4$ df …
```
=> Let sysv handle dynamic shared memory type for containers

images/manageiq-base/Dockerfile
Also allows us to use git 2.39.3-1.el8_8
https://access.redhat.com/errata/RHSA-2023:3246
=> Removing perl* exclude as there are no longer conflicts

.github/workflows/build_pods.yaml, bin/build_hotfix, images/manageiq-base-worker/Dockerfile, images/manageiq-hotfix/Dockerfile, images/manageiq-orchestrator/Dockerfile, images/manageiq-ui-worker/Dockerfile, images/manageiq-webserver-worker/Dockerfile, lib/tasks/release.rake, manageiq-operator/config/crd/bases/manageiq.org_manageiqs.yaml
Fix for some missing changes in the quinteros branch and updating the release.rake script and fixes test failures for the branch
=> [quinteros] branching followup

images/manageiq-base-worker/Dockerfile, images/manageiq-hotfix/Dockerfile, images/manageiq-orchestrator/Dockerfile, images/manageiq-ui-worker/Dockerfile, images/manageiq-webserver-worker/Dockerfile, lib/tasks/release.rake
Forward-port of https://github.com/ManageIQ/manageiq-pods/pull/982
=> quinteros branching followup

images/manageiq-base/Dockerfile
/etc/yum.repos.d/ubi.repo is missing from
registry.redhat.io/ubi8:8.8-1032.1692772289(latest) for PPC64le
latest minimal, micro and s2i-core are fine
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=2233877
Related: https://github.com/ManageIQ/manageiq-rpm_build/pull/416
=> Lock down to UBI 8.8-1032

manageiq-operator/internal/controller/manageiq_controller.go
- Kafka and zookeeper network policies should only be deployed when `deployMessagingService: true`
@miq-bot add_label bug
=> Deploy Kafka network policies only when needed

images/manageiq-base/Dockerfile
This reverts commit d8a667c4d638b5eccfc5d199f140be80485350c2.
A new UBI8 image has been released. The yum repos are available on ppc64le now.
Related:
- https://github.com/ManageIQ/container-httpd/pull/84
- https://github.com/ManageIQ/container-memcached/pull/22
- https://github.com/ManageIQ/manageiq-rpm_build/pull/419
=> Revert "Lock down to UBI 8.8-1032"

manageiq-operator/api/v1alpha1/helpers/miq-components/rbac.go
Fixes:
```
cannot get resource "pods/log" in API group "" in the namespace...
```
=> Add permissions for pods/logs to the manageiq-automation role

manageiq-operator/config/rbac/role.yaml, manageiq-operator/internal/controller/manageiq_controller.go
Followup to #999 
Fixes:
```
2023-10-10T16:16:02Z	ERROR	Reconciler error	{"controller": "manageiq", "controllerGroup": "manageiq.org", "controllerKind": "ManageIQ", "ManageIQ": {"name":"manageiq-sample","namespace":"miq"}, "namespace": "miq", "name": "manageiq-sample", "reconcileID": "8c9e0471-2231-4d18-ac75-7ef1530ccaed", "error": "roles.rbac.authorization.k8s.io \"manageiq-automation\" is forbidden: user \"system:serviceaccount:miq:manageiq-operator\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:miq\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"\"], Resources:[\"pods/logs\"], Verbs:[\"get\"]}"} sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler …
```
=> Give the operator permission to give permission to pod/logs get

manageiq-operator/api/v1alpha1/helpers/miq-components/httpd.go, manageiq-operator/api/v1alpha1/helpers/miq-components/kafka.go, manageiq-operator/api/v1alpha1/helpers/miq-components/memcached.go, manageiq-operator/api/v1alpha1/helpers/miq-components/operator.go, manageiq-operator/api/v1alpha1/helpers/miq-components/orchestrator.go, manageiq-operator/api/v1alpha1/helpers/miq-components/postgresql.go, manageiq-operator/api/v1alpha1/miqutils/find.go, manageiq-operator/api/v1alpha1/miqutils/node_affinity.go, manageiq-operator/config/manager/manager.yaml, manageiq-operator/internal/controller/manageiq_controller.go
For OpenShift 4.14 support
Part of #988
=> Add Node affinity

manageiq-operator/api/v1alpha1/helpers/miq-components/util.go
In kubernetes it is not possible to mount multiple volumes with the same mount path i.e. mount volume paths must be unique. Therefore added the edge case where if another volume is to be added that has the same mount path as an existing volume, the old volume is replaced
Needed for:
- https://github.com/ManageIQ/manageiq-pods/pull/1005
=> Add or update unique volume mount

manageiq-operator/api/v1alpha1/helpers/miq-components/util.go
similar to `addAnnotations` but for labels
@miq-bot assign @bdunne 
=> AddLabels util function

images/manageiq-orchestrator/container-assets/entrypoint, manageiq-operator/api/v1alpha1/helpers/miq-components/cr.go, manageiq-operator/api/v1alpha1/manageiq_types.go, manageiq-operator/config/crd/bases/manageiq.org_manageiqs.yaml
- Enforce Kafka by making the orchestrator wait for Kafka service to be ready (requires Kafka network policy)
- default `deployMessagingService` to true from CR as Kafka will be the default configuration -> this will retain the option to disable Kafka in case things go wrong
Depends on:
Needed for:
Ref:
- https://github.com/ManageIQ/manageiq/issues/22225
@miq-bot assign @Fryguy 
@miq-bot add_reviewer @agrare
=> Enforce and default Kafka configuration

manageiq-operator/api/v1alpha1/miqutils/find.go
The `FindCatalogSourceByName` was returning an empty catalog source object if the catalog source was not found instead of returning `nil` i.e. (from debug logging)
```
{"result": {"metadata":{"creationTimestamp":null},"spec":{"sourceType":"","icon":{"base64data":"","mediatype":""}},"status":{}}}
```
This was nullifying the openshift checks we have in place for deploying the strimzi operator https://github.com/ManageIQ/manageiq-pods/blob/master/manageiq-operator/internal/controller/manageiq_controller.go#L529
In addition it was found that the following error is thrown if performing a `client.Get()` call on a resource for which the CRDs are not installed (instead of throwing errors.IsNotFound()):
```
failed to get restmapping: no matches for kind \"CatalogSource\" in group …
```
=> Error handling for FindCatalogSourceByName

manageiq-operator/api/v1alpha1/helpers/miq-components/cr.go
Depends on:
- https://github.com/ManageIQ/container-httpd/pull/86
- https://github.com/ManageIQ/container-memcached/pull/24
- https://github.com/ManageIQ/container-postgresql/pull/59
=> Add OS release version to our image tags

manageiq-operator/api/v1alpha1/helpers/miq-components/generators.go
Password decryption can fail if the database password is all numbers because ruby will read it as an integer instead of a string.
```
== Checking deployment status ==
rake aborted!
NoMethodError: undefined method `empty?' for 8783875645714351:Integer 
.../gems/manageiq-password-1.2.0/lib/manageiq/password.rb:165:in `remove_erb' 
.../gems/manageiq-password-1.2.0/lib/manageiq/password.rb:90:in `try_decrypt' 
/var/www/miq/vmdb/lib/vmdb/settings_walker.rb:76:in `block in decrypt_passwords!'
```
=> Only return passwords that include letters.

.gitignore, bin/build, images/manageiq-base/Dockerfile, images/manageiq-base/container-assets/prepare_local_yum_repo.sh, images/manageiq-rpms/Dockerfile, images/manageiq-webserver-worker/Dockerfile
This allows the RUN command that need then to mount that image, without actually including the RPM artifacts in the final image itself.
This PR introduces a new image, manageiq-rpms, into which copied RPMs will go.  Later stages can reuse this image when they need to install RPMs.  This avoids having a layer with the COPY'd RPMs and then another layer with their contents installed.  In my estimation this will knock out around 400MB of wasted image space.
=> Move RPM copying into a separate image

images/manageiq-base-worker/Dockerfile, images/manageiq-base/Dockerfile, images/manageiq-orchestrator/Dockerfile, images/manageiq-ui-worker/Dockerfile, images/manageiq-webserver-worker/Dockerfile
MAINTAINER is a deprecated command, and LABELs are preferred. We already have vendor and url labels with this same information.
@bdunne Please review.
=> Drop MAINTAINER docker commands

images/manageiq-base/Dockerfile
This reverts commit e93d917a529e5675908ad0228386e87849c059d5, reversing changes made to a4c927cf384542a9a483415a705f03a8d3a76b85.
Depends on: https://github.com/ManageIQ/manageiq-rpm_build/pull/458
It turns out that upgrading to openssl v3.2 did not fix our problems, instead we're going to lock down to <v3.2
=> Revert "Merge pull request #1096 from bdunne/openssl_fix"

manageiq-operator/api/v1alpha1/helpers/miq-components/network_policies.go
Updated network policy to consider updated label i.e. `service: opentofu-runner`
=> Updated PodSelector label to opentofu-runner

manageiq-operator/internal/controller/manageiq_controller.go
This should be checking whether we found objectSecret before continuing, we wouldn't be here if object was nil.
```
2024-05-17T17:14:52Z	INFO	controller_manageiq	Reconciling the CR status... 2024-05-17T17:14:52Z	INFO	Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"controller": "manageiq", "controllerGroup": "manageiq.org", "controllerKind": "ManageIQ", "ManageIQ": {"name":"im-iminstall","namespace":"cp4aiops"}, "namespace": "cp4aiops", "name": "im-iminstall", "reconcileID": "9b4b34f7-5f38-4a68-aad7-858b417ce57e"} panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15665c0] …
```
=> Fix nil pointer dereference error

images/manageiq-base/Dockerfile
Related: https://github.com/ManageIQ/manageiq-rpm_build/pull/467
Unfortunately the repos RPM in the vault still points to mirrors.centos.org which is no longer serving Stream 8.  I patched the RPMs and posted them on rpm.manageiq.org with a change to point all repos to the vault.
=> [morphy] CentOS Stream 8 is EOL

manageiq-operator/api/v1alpha1/helpers/miq-components/httpd.go
If someone were to successfully install the application then delete the TLSSecret, the operator would not recreate it because it detected that the Database Secret already existed.  This will cause errors during reconcile when the operator tries to update the CR status.  Instead, we should be checking the existence of the TLS Secret.
=> Fix bug in TLS secret detection

manageiq-operator/api/v1alpha1/helpers/miq-components/cr.go, manageiq-operator/api/v1alpha1/manageiq_types.go, manageiq-operator/config/crd/bases/manageiq.org_manageiqs.yaml
=> Kafka and Zookeeper images are no longer used

manageiq-operator/README.md
Trying to test out some miq_server changes and ran into this, believe it should be updated to match https://github.com/ManageIQ/manageiq-pods/pull/831/commits/b25cbb2f0eae71f23c38211d2c7eb204ca56127c#diff-6d4414c4f9d176009160c46934a42c9cc20803940e97af41e93fdd04509a6021L37-R37
I'm still having issues deploying a custom operator but I think that is unrelated to this
=> Fix the path for `oc create -f` custom operator

.github/workflows/build_pods.yaml
`ubuntu-latest` still points to 22.04 which has podman 3.4.4 and run in that version does not support bind mounting volumes.  Upgrading to 24.04 gets us podman 4.9.3
Error:
```
error resolving mountpoints for container "4349440300a7f09982c00e0a8d5a010141b5eb912483ea6646bacaf54c080194": invalid mount type "bind"
```
=> Switch to ubuntu-24.04

manageiq-operator/Dockerfile, manageiq-operator/go.mod
Drop the toolchain and move minimum to 1.23
"If the toolchain line is omitted, the module or workspace is considered to have an implicit toolchain goV line, where V is the Go version from the go line." -https://go.dev/doc/toolchain
=> Update go to v1.23

manageiq-operator/api/v1alpha1/helpers/miq-components/postgresql_conf.go
Similar PR to https://github.com/ManageIQ/manageiq-appliance/pull/388, but for containerized.
=> Default the system password_encryption to scram-sha-256

manageiq-operator/api/v1alpha1/helpers/miq-components/httpd.go, manageiq-operator/internal/controller/manageiq_controller.go
If routes are not available, use kubernetes ingress. If certificates are available for pod-to-pod communication, set the route to reencrypt.  If not available, set the route to edge termination using the wildcard certificate on the cluster.
CP4AIOPS-1224
=> If routes are available, prefer them and use cluster default certificate

manageiq-operator/api/v1alpha1/helpers/miq-components/orchestrator.go, manageiq-operator/api/v1alpha1/helpers/miq-components/util.go, manageiq-operator/internal/controller/manageiq_controller.go
- Refactor labeling methods
- Ensure pods are restarted when certificates are renewed
- Watch for changes to the cr.Spec.InternalCertificatesSecret secrets 
CP4AIOPS-5110
=> Restart pods on certificate renewal

images/manageiq-base-worker/container-assets/entrypoint
Workers having a comma separated list of EMS IDs is no longer used and this can be simplified to a single EMS_ID.
Co-depends:
* https://github.com/ManageIQ/manageiq/pull/23195
=> Replace EMS_IDS with EMS_ID in container entrypoint

manageiq-operator/api/v1alpha1/helpers/miq-components/httpd.go, manageiq-operator/internal/controller/manageiq_controller.go
- If routes are installed in the cluster, add a watch for them
- If we are using routes, ensure that we do not have an ingress.
- Remove manually set certificates on routes and use the cluster default
CP4AIOPS-6311
=> Watch routes and ingress, ensure we're only using one

images/manageiq-base/Dockerfile
Unfortunately the repos RPM in the vault still points to mirrors.centos.org which is no longer serving Stream 8.  I patched the RPMs and posted them on rpm.manageiq.org with a change to point all repos to the vault.
Forward-port of https://github.com/ManageIQ/manageiq-pods/pull/1118
=> [quinteros] CentOS Stream 8 is EOL

manageiq-operator/Dockerfile, spec/manageiq-operator/go_version_spec.rb
- speed up build since there is less to download
- reduce external dependencies
- build and run on the same base image
```
REPOSITORY                TAG  IMAGE ID     CREATED         SIZE
my                        test 422e3c099772 10 seconds ago  366 MB
docker.io/library/golang  1.23 361d8b5c9aa5 3 weeks ago     862 MB
```
=> Prefer UBI and go download over library/golang

manageiq-operator/api/v1alpha1/helpers/miq-components/httpd_conf.go
The receiving end (ruby code) will use this delimiter to separate classes. Since the various components use different delimiters, it is easiest to configure this in one place and pass it around
see also https://github.com/ManageIQ/manageiq/pull/23139
=> CP4AIOPS-3113 pass delimiter for groups

images/manageiq-base/Dockerfile
Previously we were stuck at 2.43.0-1.el8, with this change we can get 2.43.5-2.el8_10
This reverts https://github.com/ManageIQ/manageiq-pods/pull/722 now that CentOS 8 Stream has older packages than RHEL/UBI
CP4MCM-131
=> [morphy] upgrade git

manageiq-operator/go.mod
It's not necessary and we can just use the go version 
Closes #1199
=> remove toolchain

.github/workflows/build_pods.yaml
This reverts commit b679e50f964d3742588a9c4c0f5b404cc7660780.
ubuntu-latest now points to ubuntu-24.04
=> Revert "Switch to ubuntu-24.04"

manageiq-operator/go.mod, manageiq-operator/go.sum
Fix security issue: https://jsw.ibm.com/browse/CP4MCM-1518
go get golang.org/x/net@v0.23.0
go get k8s.io/client-go/plugin/pkg/client/auth/exec@v12.0.0+incompatible
go get github.com/prometheus/procfs@v0.6.0
go mod tidy
Related issue: https://github.ibm.com/IBMPrivateCloud/ibm-infra-management-install-operator/pull/648
=> [MORPHY] Upgrade golang.org/x/net version to 0.23.0

manageiq-operator/api/v1alpha1/helpers/miq-components/httpd.go, manageiq-operator/api/v1alpha1/helpers/miq-components/memcached.go, manageiq-operator/api/v1alpha1/helpers/miq-components/orchestrator.go, manageiq-operator/api/v1alpha1/helpers/miq-components/postgresql.go
The maps.Copy function syntax is maps.Copy(dest, src). Currently we have the wrong order. Fixing it.
https://pkg.go.dev/maps#Copy
=> Update the maps.Copy operands.

images/manageiq-base/container-assets/container_env
Helpful discussion in https://bugzilla.redhat.com/show_bug.cgi?id=2241240
CP4AIOPS-11300
=> Fix update-ca-trust error - p11-kit: couldn't make directory writable

manageiq-operator/go.mod
Can't backport https://github.com/ManageIQ/manageiq-pods/pull/1244 because of the other dependencies included in it.
=> [morphy] upgrade go

manageiq-operator/Dockerfile
Handle cases where go.mod contains "go 1.24.0" or "go 1.24" and pick the latest patch version for that major.minor.
Previously this was picking up the whole of "go1.24.0" and locking us down to that minimum version
=> Only pick the major and minor go version to ensure the latest is pulled

images/manageiq-orchestrator/container-assets/entrypoint
When the builtin automate domain is updated the domain has to be reset by running `rake evm:automate:reset`
This was missing from the orchestrator upgrade process causing changes to the automate domain to not be applied when upgrading and existing deployment.
=> Add missing evm:automate:reset on upgrade

.github/workflows/build_pods.yaml, .github/workflows/ci.yaml, .github/workflows/go_dependencies.yaml
Unfortunately it looks like we need to specify the z-version of go now... this will keep it up to date.
https://github.com/ManageIQ/manageiq-pods/actions/runs/15949770344/job/45082004161
=> Run with the latest go version
