ManageIQ/manageiq-pods

- images/miq-app/Dockerfile
- templates/miq-template.yaml
- Modified template to mount a persistent volume for the MIQ application pod
- Modified image to create necessary volume mount path for persistent volume
- Added a volume capacity parameter for MIQ data
- Fixed a few minor template parameter description format issues
> Add PV for MIQ data

- images/miq-app/ose-assets/appliance-initialize.sh
- templates/miq-template.yaml
- Parametize DB region on template and adjust appliance-initialize for proper handling
> Add DATABASE_REGION parameter to deployment template

- images/miq-app/ose-assets/appliance-initialize.sh
- Cleanup for now, we need to re-work this better to accomodate the docker-compose contrib
> Cleanup docker-compose calls on appliance-initialize

- images/miq-app/Dockerfile
- Added IMAGE_VERSION based on $REF at build-time, this would be used for OSE deployment validation tasks
> Added IMAGE_VERSION to miq-app image

- templates/miq-template.yaml
- Added description to most parameters and APPLICATION_DOMAIN
> Added APPLICATION_DOMAIN param and other minor template fixes

- images/miq-app/docker-assets/appliance-stop-post.sh
- images/miq-app/docker-assets/container-deploy-common.sh
- Re-root all persistent data in /persistent/container-data instead of /persistent
> Adjust data dir to container-data on PV

- images/miq-app/docker-assets/appliance-initialize.sh
- images/miq-app/docker-assets/container-deploy-common.sh
- The backup_pv_data function will run pre-upgrade to ensure original contents of PV are intact
- Added sub-shells w/ tee to restore_pv_data and backup_pv_data functions to ensure additional logging
> Added backup_pv_data function to upgrade procedure

- images/miq-app/docker-assets/container-deploy-common.sh
- check_version_gt will ensure that the upgrade version is actually newer than the PV recorded version
- It supports numeric and alphanumeric versioning (upstream/downstream)
- If the upgrade version is actually older than the PV version, it will abort the upgrade
> Added check_version_gt function

- images/miq-app/Dockerfile
- images/miq-app/docker-assets/container-deploy-common.sh
- images/miq-app/docker-assets/post-upgrade
- images/miq-app/docker-assets/pre-upgrade
@bazulay @carbonin Gents, please review, these are sample hook scripts, we will implement logic once the use cases arise.
> Add hook sample scripts

- images/miq-app/Dockerfile
Related PR: https://github.com/ManageIQ/manageiq/pull/12263
> Rename SSUI to SUI

- images/miq-app/Dockerfile
Related PR: https://github.com/ManageIQ/manageiq/pull/12730
> Update SUI build steps to use yarn and gulp

- templates/miq-template.yaml
Master PR: https://github.com/ManageIQ/manageiq-pods/pull/73
Cherry-picked and changed *_IMG_TAG to point to euwe.
> [EUWE] Use manageiq/manageiq-pods images

- images/miq-app/Dockerfile
> added openscap-scanner rpm

- templates/miq-template.yaml
Fixes https://github.com/ManageIQ/manageiq-pods/issues/82
> Add missing $ for APPLICATION_IMG_TAG

- images/miq-app/Dockerfile
Related PR: ManageIQ/manageiq-appliance-build#189
The same change for monolithic: https://github.com/ManageIQ/manageiq/pull/13590
> Update Service UI build command

- images/miq-app/Dockerfile
https://bugzilla.redhat.com/show_bug.cgi?id=1406804
Related PR: ManageIQ/manageiq-appliance-build#138
For monolithic: https://github.com/ManageIQ/manageiq/pull/13477
> Cleanup logs after build

- README.md
@bazulay @simaishi Please review, fixes #86
> Update doc img bulk import

- templates/miq-template.yaml
> Parametrize the container image names

- README.md
- Provide cluster sizing guidelines for MIQ deployments on OpenShift
> Documentation update, add minimum sizing for Openshift clusters

- images/miq-app/docker-assets/container-scripts/container-deploy-common.sh
- Handle master special upgrade/redeploy case properly
- Added conditional to check for supplied master DB schema and compare against DB
- If both schemas are identical, proceed with redeploy, if master image schema is newer, proceed with upgrade
> Do not always force upgrade for master builds

- images/miq-app/Dockerfile
Not having log/apache dir causes issue on startup (apache 503 error)
> Need to leave log/apache dir, delete log/*.log only

- README.md
- Increase indentation on sections to allow proper parsing by GH
> Minor doc format fixes on README

- images/miq-app/docker-assets/appliance-initialize.sh
- images/miq-app/docker-assets/container-scripts/container-deploy-common.sh
- Avoid unnecessary db migration on redeployment/reschedule case
> Do not migratedb on re-redeployment case

- images/miq-app/Dockerfile
- See https://github.com/ManageIQ/manageiq/pull/14536
> MIQ app Dockerfile fix bower relocation

- images/miq-app/Dockerfile
https://github.com/ManageIQ/manageiq-appliance-build/pull/207
> Only install production dependencies for SUI

- README.md
The correct file has the "yaml" extension
> Fix master-config.yaml extension

- images/miq-app/docker-assets/container-scripts/container-deploy-common.sh
- templates/miq-template-ext-db.yaml
- templates/miq-template.yaml
@bazulay @durandom @carbonin Please review, now processing DATABASE_NAME in MIQ pod.
> Miq pod fix custom db name

- images/miq-app/docker-assets/container-scripts/container-deploy-common.sh
The server should pull the region number from the database
> Once the DB is initialized, we shouldn't need the REGION file

- README.md
> Fix references to the privileged scc

- templates/miq-template-ext-db.yaml
We run with anyuid as of #140
See commits a4f50aadb95f2c1b3d132e1d3a98acbd3e5f4649 and 2d1dd53b56e3d826791a5627d3c0adc5f81672f2
> Remove privileged security context from external database template

- images/miq-app/docker-assets/container-scripts/container-deploy-common.sh
- templates/miq-template-ext-db.yaml
- templates/miq-template.yaml
DATABASE_URL is built into Rails and reduces a lot of the complexity of ENV variables and maintaining database.yml in multiple locations.  It seems like the best solution for production deployments.
> Remove all database environment variables in favor of DATABASE_URL

- images/miq-app/docker-assets/appliance-initialize.sh
- images/miq-app/docker-assets/container-scripts/container-deploy-common.sh
- templates/miq-template-ext-db.yaml
- templates/miq-template.yaml
This allows us to remove one more thing from the region PV and gives us sharing of the v2_key for free.
This gets us closer to removing the shared region PV entirely
> Move the v2_key from a file to a secret

- templates/miq-template-ext-db.yaml
- templates/miq-template.yaml
Based on changes in: https://github.com/ManageIQ/container-httpd/pull/6
> Pass ENV variables for service endpoints

- images/miq-app-frontend/Dockerfile
- images/miq-app/Dockerfile
- templates/miq-template-ext-db.yaml
- templates/miq-template.yaml
Dockerfile cleanup and add a timeoutSeconds to the backend stateful set
> Dockerfile cleanup

- README.md
- images/miq-app/docker-assets/container-scripts/container-deploy-common.sh
- templates/miq-template-ext-db.yaml
- templates/miq-template.yaml
Backport to fine branch of #119 and #135 
cc @gtanzillo @bazulay @fbladilo @sdodson @joelddiaz
> [FINE] Deploy MIQ using external PG database

- teardown
> Add the new ConfigMap and service account to the teardown script

- images/miq-app/docker-assets/container-scripts/container-fix-permissions
@bdunne Cleanup old assets, as a bonus should kick a new build 😄
> Cleanup unnecessary container-fix-permissions script from docker assets

- README.md
@carbonin @bdunne Some cleanup and minor updates..
> Documentation cleanup/update

- README.md
- templates/miq-template-ext-db.yaml
- templates/miq-template.yaml
changing miqsp -> sp
updated README.md example.
Depends on: https://github.com/ManageIQ/httpd_configmap_generator/pull/19
> Removing miq references from the httpd SAML config files.

- .travis.yml
These are the current versions we support
> Fix Rubies

- CHANGELOG.md
> [Changelog] Update for Sprint 72

- images/miq-app/Dockerfile
We forgot to change this to Master/Gaprindashvili, it's all pointing to `Fine` repo.
@Fryguy Another item to add to your list for post-branching tasks.
Related PR: https://github.com/ManageIQ/manageiq-appliance-build/pull/230
> Change copr repo to Master

- templates/miq-template-ext-db.yaml
- templates/miq-template.yaml
> Add artemis service

- images/manageiq-orchestrator/docker-assets/appliance-initialize.sh
- templates/miq-template-ext-db.yaml
- templates/miq-template.yaml
The script for checking the database and memcached services should be taking care of this concern
> Remove 15 second sleep from startup time

- README.md
- images/miq-app-frontend/Dockerfile
- images/miq-app/Dockerfile
- images/miq-app/container-assets/appliance-initialize.sh
- templates/miq-template-ext-db.yaml
- templates/miq-template.yaml
Trying to put together the changes we need to make a hammer branch.
We won't merge this, but it will be easy to see like this before we actually go and create the branch.
> [HAMMER] Backport enhancements made to master since Gaprindashvili

- templates/miq-template-ext-db.yaml
- templates/miq-template.yaml
> [HAMMER] Add the artemis username and password to the frontend pod

- README.md
- images/miq-app-frontend/Dockerfile
- images/miq-app/Dockerfile
- templates/miq-template-ext-db.yaml
- templates/miq-template.yaml
> [HAMMER] Updates for Hammer branch release

- README.md
> PostgreSQL 9.4 no longer supported, remove reference

- images/miq-app/Dockerfile
container image version of https://github.com/ManageIQ/manageiq-appliance-build/pull/236
Closes https://github.com/ManageIQ/manageiq/issues/18503
> Add BUILD file

- README.md
- images/miq-app-frontend/Dockerfile
- images/miq-app/Dockerfile
- templates/miq-template-ext-db.yaml
- templates/miq-template.yaml
"I" branch version of https://github.com/ManageIQ/manageiq-pods/pull/306 + image tag updates
> [IVANCHUK] Updates for Ivanchuk release

- images/miq-app-frontend/Dockerfile
Making the image tag ARG so we can pass different values for tagged build.
> Set IMAGE_REF

- images/miq-app-frontend/Dockerfile
- images/miq-app/Dockerfile
Also moved npm install to frontend and removed 'bower' (removed from appliance in
https://github.com/ManageIQ/manageiq-ui-classic/pull/4735)
As discussed... I tested the final monolithic image only.
> Removed duplicate UI related work from backend

- .gitignore
- templates/app/httpd.yaml
- templates/app/memcached.yaml
- templates/app/orchestrator.yaml
- templates/app/postgresql.yaml
- templates/app/secrets.yaml
- templates/build-template.yaml
YAML likes bonus quotes around the parameters.
> Fix dump and restore specs

- images/manageiq-ui-worker/Dockerfile
Podified image version of https://github.com/ManageIQ/manageiq-appliance-build/pull/365
> Remove 'yarn cache clean' workaround

- bin/build
- images/manageiq-base/Dockerfile
Adds support for specifying a particular Github endpoint and Github token.
Issue: https://github.com/ManageIQ/manageiq-pods/issues/358
> Add support for github enterprise

- images/manageiq-base/Dockerfile
Appliance build PR: https://github.com/ManageIQ/manageiq-appliance-build/pull/394
> Update to ruby 2.6

- templates/ops/miq-restore-job.yaml
Forgot to change this after testing #393
Thanks for catching this @simaishi
> Use manageiq image for restore job

- .travis.yml
> Add build step to Travis

- manageiq-operator/README.md
> Updated readme for ManageIQ operator

- manageiq-operator/README.md
- manageiq-operator/deploy/crds/manageiq_v1alpha1_manageiq_cr.yaml
- manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
- manageiq-operator/pkg/helpers/miq-components/httpd.go
- manageiq-operator/pkg/helpers/miq-components/memcached.go
- manageiq-operator/pkg/helpers/miq-components/orchestrator.go
- manageiq-operator/pkg/helpers/miq-components/postgresql.go
Also Capitalize Cpu correctly in variable names
Fixes #408
> Don't abbreviate Memory, Image, and Request

- manageiq-operator/deploy/crds/manageiq_v1alpha1_manageiq_cr.yaml
- manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
- manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
- manageiq-operator/pkg/helpers/miq-components/generators.go
- manageiq-operator/pkg/helpers/miq-components/kafka.go
- manageiq-operator/pkg/helpers/miq-components/postgresql.go
- templates/app/kafka.yaml
> Deploy kafka from the operator

- manageiq-operator/pkg/helpers/miq-components/httpd.go
- manageiq-operator/pkg/helpers/miq-components/postgresql.go
Fixed path-names for configmap data sources
> Fixes #427

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
> Added issue and pr template

- .github/PULL_REQUEST_TEMPLATE.md
Addressing comments at https://github.com/ManageIQ/manageiq-pods/pull/433#discussion_r407542046
FYI @carbonin @chessbyte 
Fixes #
> Remove release note from pull requset template.

- manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
> Regenerate crds to pick up new API field.

- manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml
- manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml
- manageiq-operator/deploy/olm-catalog/manageiq-operator/manageiq-operator.package.yaml
Fixes part of https://github.com/ManageIQ/manageiq-pods/issues/415
Those files are generated by command as follows:
```
operator-sdk generate csv --csv-version 0.0.1 --update-crds
```
FYI @carbonin @Fryguy
> Added olm files

- manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml
Missed this. We're really gonna need to get this into CI ... :sob:
> Regenerate the csv files after #449

- manageiq-operator/pkg/helpers/miq-components/httpd.go
This was missing from the first pass of the operator
Fixes #457
> Add missing httpd readiness probe

- manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
- manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml
- manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
- manageiq-operator/pkg/helpers/miq-components/orchestrator.go
This is the operator side of #456
Note: I used a string type on purpose here to distinguish between
unset and the value 0
> Parameterize the orchestrator liveness probe initial delay in the operator

- images/manageiq-base/Dockerfile
BUILD file is needed in container image to show SUI version in About screen.
Requires https://github.com/ManageIQ/manageiq-ui-service/pull/1636
cc @himdel Thank you for adding the support!
> Create BUILD file for SUI

- manageiq-operator/pkg/helpers/miq-components/orchestrator.go
- templates/app/orchestrator.yaml
This will be used to deploy the worker containers with the
same tag
https://github.com/ManageIQ/manageiq-pods/issues/464
Merge with https://github.com/ManageIQ/manageiq/pull/20094
> Send the image tag to the operator

- bin/build
- images/manageiq-base/Dockerfile
- images/manageiq-ui-worker/Dockerfile
**What this PR does / why we need it**: Fix build failures on ppc64le
**Which issue(s) this PR fixes** https://github.com/ManageIQ/manageiq-pods/issues/460
Fixes #460 
- Build passes, all the docker images are created successfully.
- Build for top level manageiq image passes, image runs without errors, login via GUI using default credentials succeed
> Fix build failures on Power

- bin/build
> Add operator to build script

- manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
- manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml
- manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
- manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Set this to a secret containing the information required to pull
the manageiq application images.
Fixes #472
This is really the operator side of https://github.com/ManageIQ/manageiq-pods/pull/370
> Create an ImagePullSecret parameter in the CR

- manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
- manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml
- manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
- manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
This is the operator version of https://github.com/ManageIQ/manageiq-appliance/pull/282
cc @jvlcek @abellotti 
Going to leave this as WIP until all the details are worked out in https://github.com/ManageIQ/manageiq-appliance/pull/282
This should get us full UI and API support for OIDC auth.
> Add OIDC config to allow for API access

- manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml
> Updated olm

- manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Fixes https://github.com/ManageIQ/manageiq-pods/issues/497
/cc @carbonin
> Enable region customization

- .travis.yml
**What this PR does / why we need it:** Add travis jobs for ppc64le architecture.
**Special notes for your reviewer:**
- Build passes: https://travis-ci.org/github/Siddhesh-Ghadi/manageiq-pods/builds/688274723
> Add Power support on travis-ci

- manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
- manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml
- manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
- manageiq-operator/pkg/helpers/miq-components/kafka.go
- manageiq-operator/pkg/helpers/miq-components/postgresql.go
Fixes https://github.com/ManageIQ/manageiq-pods/issues/488
> enable setting storageclass

- bin/build
- images/manageiq-base/Dockerfile
- images/manageiq-ui-worker/Dockerfile
> Allow rpm prefix to be changed

- bin/build
> Use branch specific rpm build image

- manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
- manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq.org_manageiqs_crd.yaml
- manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
- manageiq-operator/pkg/helpers/miq-components/kafka.go
Fixed https://github.com/ManageIQ/manageiq-pods/issues/527
> Enable customization for kafka and zookeeper image

- manageiq-operator/go.mod
- manageiq-operator/go.sum
Fixed https://github.com/ManageIQ/manageiq-pods/issues/533
FYI @carbonin @Fryguy
> remove package dependency bou.ke/monkey

- manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
- manageiq-operator/pkg/helpers/miq-components/postgresql.go
- manageiq-operator/pkg/helpers/miq-components/util.go
handles updating postpresql resources 
Applies to #438
> Change Postgresql component to support CreateOrUpdate

- manageiq-operator/pkg/helpers/miq-components/memcached.go
- manageiq-operator/pkg/helpers/miq-components/postgresql.go
> Don't change the deployment spec labels and selectors in mutate

- manageiq-operator/deploy/operator.yaml
Based on conversation in https://github.com/ManageIQ/manageiq-pods/pull/545
> [JANSA] Always pull latest tags

- images/miq-app/Dockerfile
Fixes https://github.com/ManageIQ/manageiq/issues/20273
> [IVANCHUK] Add ansible/ansible-runner

- manageiq-operator/README.md
- templates/app/kafka-secrets.yaml
- templates/app/postgresql-secrets.yaml
> Document customizing secrets for Postgres and messaging

- manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
Add OIDC Support for the Self-Service UI
> Add OIDC support for the Self-Service UI

- manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
- manageiq-operator/pkg/helpers/miq-components/kafka.go
Allow the Kafka and Zookeeper objects to be updated
Addresses part of https://github.com/ManageIQ/manageiq-pods/issues/438
> Add reconcile functions to Kafka and Zookeeper

- manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
- manageiq-operator/pkg/helpers/miq-components/orchestrator.go
> Allow orchestrator to be updated during reconcile

- manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
- manageiq-operator/pkg/helpers/miq-components/httpd.go
> Allow httpd Services, Deployment and ConfigMap to be reconciled

- manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
Fixes #574 
Built on top of #572
> Dont log unchanged results

- manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
- manageiq-operator/pkg/helpers/miq-components/httpd.go
- manageiq-operator/pkg/helpers/miq-components/kafka.go
- manageiq-operator/pkg/helpers/miq-components/memcached.go
- manageiq-operator/pkg/helpers/miq-components/orchestrator.go
- manageiq-operator/pkg/helpers/miq-components/postgresql.go
- manageiq-operator/pkg/helpers/miq-components/rbac.go
Use a service account for pull secrets
@bdunne can you look through this to ensure it's a good enough translation?
Master PR: #579
> [JANSA] Use a service account for pull secrets

- images/manageiq-base/Dockerfile
This PR will solve the IBM Cloud vulnerabilities issues for managiq images !  
dnf upgrade command will ensure that the image has the packages upgraded to the latest .  This upgrade will fix eventual security vulnerabilities for the OS .  
N/A
@miq-bot add-label bug
> adding package update command

- manageiq-operator/README.md
- manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml
@bdunne do you think it would be useful to go through all the steps to get the operator into the openshift operator hub SUI-type thing here? Or is that not something we're going to do for this project?
> Add operator bundle instructions to README

- bin/build
- images/manageiq-base/Dockerfile
Podified build version of https://github.com/ManageIQ/manageiq-appliance-build/pull/425
> Do not add nightly yum repo in release build

- templates/miq-template-ext-db.yaml
- templates/miq-template.yaml
Updated the HTTPD config file for external authentication to properly reset the headers.
> [IVANCHUK] Properly reset HTTPD headers

- manageiq-operator/README.md
This PR enhances the README based on the experiences of an  inexperienced OpenShift operator user, me, attempting to follow it.
I also added a description for configuring OIDC
> Enhance the README and add a description for deploying with OIDC

- manageiq-operator/README.md
> Fix typo of key name in example

- README.md
> Document allowing manageiq images in kubernetes

- .travis.yml
- images/manageiq-base-worker/container-assets/entrypoint
Needed for https://github.com/ManageIQ/manageiq/pull/20792
> Pass pod hostname as system-uid option to run_single_worker.rb

- images/manageiq-base/Dockerfile
Missed in the previous PR #660
> Update to UBI 8.3 #2

- manageiq-operator/deploy/olm-catalog/manageiq-operator/0.0.1/manageiq-operator.v0.0.1.clusterserviceversion.yaml
- manageiq-operator/deploy/role.yaml
- manageiq-operator/pkg/helpers/miq-components/network_policies.go
Fixes `no matches for kind "NetworkPolicy" in version "extensions/v1beta1"`
> Switch NetworkPolicies from extensions/v1beta1 to networking/v1

- images/manageiq-base/container-assets/container_env
- manageiq-operator/README.md
- manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
- manageiq-operator/pkg/helpers/miq-components/orchestrator.go
- manageiq-operator/pkg/helpers/miq-components/postgresql.go
> Support Postgres with SSL certificates

- manageiq-operator/README.md
See: https://github.com/ManageIQ/manageiq-documentation/pull/1526
> Backup and restore documentation has moved to manageiq-documentation

- bin/build
- images/manageiq-base/Dockerfile
I believe this will require a slight downstream change
> Remove no longer used HOOKS_SCRIPT_URL

- manageiq-operator/README.md
- Add an install step for creating a namespace is the user doesn't have one.
- Add uninstall steps
> Enhance Operator documentation

- images/manageiq-base/container-assets/container_env
> Disable gems when escaping for URL

- manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
- manageiq-operator/pkg/helpers/miq-components/httpd.go
Based on https://github.com/ManageIQ/manageiq-pods/pull/692#issuecomment-796967341
> [Kasparov] Cherry-pick of #692

- manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
Now it only logs to stdout / stderr, no files
Related to https://github.com/ManageIQ/container-httpd/pull/57
> This wasn't logging to stdout and we don't need the files

- images/manageiq-base/Dockerfile
Even though this is moot when #636 is merged, this makes things a little nicer.
@bdunne Please review.
> Name the stage for easier reference

- manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Image names can change in the CR and the running operator should update those on the orchestrator deployment.
> Ensure worker image env vars are updated during reconcile

- manageiq-operator/pkg/helpers/miq-components/orchestrator.go
Based on https://github.com/ManageIQ/manageiq-pods/pull/708
Ensure that the orchestrator image is also updated if changed in the CR
> Update orchestrator image

- manageiq-operator/pkg/helpers/miq-components/orchestrator.go
If any of these values changed previously, they would not re-deploy the orchestrator with the changes
> Reconcile Orchestrator ENV vars

- images/manageiq-ui-worker/container-assets/manageiq-http.conf
- manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
remove unnecessary headers which may help attackers in planning further attacks.
related to https://github.com/ManageIQ/manageiq-appliance/pull/314
> remove unnecessary headers

- manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
- manageiq-operator/pkg/apis/manageiq/v1alpha1/zz_generated.deepcopy.go
Based on https://github.com/ManageIQ/manageiq-pods/pull/714 and https://github.com/ManageIQ/manageiq-pods/pull/713#discussion_r626626298
> Omit any empty fields in the ManageIQSpec

- manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
- manageiq-operator/pkg/apis/manageiq/v1alpha1/zz_generated.deepcopy.go
> Sort alphabetically and fix inconsistent whitespace

- images/manageiq-base/container-assets/container_env
Based on https://github.com/ManageIQ/manageiq/pull/21214
> Switch from postgresql.crt to root.crt

- manageiq-operator/README.md
https://github.com/ManageIQ/manageiq-documentation/pull/1570
> External postgres doc added to the official documentation

- images/manageiq-base/Dockerfile
Part of https://github.com/ManageIQ/manageiq-appliance-build/issues/459
@bdunne Please review
> Move to CentOS Stream

- manageiq-operator/pkg/helpers/miq-components/cr.go
- manageiq-operator/pkg/helpers/miq-components/orchestrator.go
- manageiq-operator/pkg/helpers/miq-components/postgresql.go
Built on top of https://github.com/ManageIQ/manageiq-pods/pull/730
> Alphabetize

- images/manageiq-base/Dockerfile
- images/manageiq-base/container-assets/container_env
- Ensure that local CAs are trusted
- Install mod_ssl
> Allow running with TLS/SSL

- Gemfile
- Rakefile
- lib/tasks/release.rake
> Add branch release tasks

- manageiq-operator/deploy/crds/manageiq.org_manageiqs_crd.yaml
- manageiq-operator/deploy/olm-catalog/manageiq-operator/manifests/manageiq.org_manageiqs_crd.yaml
- manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
- manageiq-operator/pkg/helpers/miq-components/cr.go
Depends on https://github.com/ManageIQ/container-memcached/pull/8
> Switch to memcached:1 tag

- manageiq-operator/pkg/apis/manageiq/v1alpha1/manageiq_types.go
- manageiq-operator/pkg/apis/manageiq/v1alpha1/zz_generated.deepcopy.go
Merge pull request #716 from bdunne/omitempty
Omit any empty fields in the ManageIQSpec
(cherry picked from commit c89c88d4c531c976f15fdf87709116f6908989da)
> [MORPHY] Omit any empty fields in the ManageIQSpec

- .travis.yml
- lib/tasks/spec.rake
- spec/manageiq-operator/formatting_spec.rb
- spec/manageiq-operator/gofmt_spec.rb
> Add spec to check go mod tidy

- manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
Partial backport of #742
Unfortunately this was rendering things like http://localhost:3001%!{(MISSING)REQUEST_URI} rather than returning an error
> [MORPHY] Partial backport of #742

- .travis.yml
Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472
(cherry picked from commit ecbb5682072f49f23e0082b24e4ce59d5d321495)
> [MORPHY] Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472

- .travis.yml
Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472
(cherry picked from commit ecbb5682072f49f23e0082b24e4ce59d5d321495)
> [LASKER] Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472

- .travis.yml
Manual backport of https://github.com/ManageIQ/manageiq-pods/pull/757
> [KASPAROV] Switch to Ubuntu bionic, see: ManageIQ/manageiq#21472

- images/manageiq-base/Dockerfile
- images/manageiq-webserver-worker/Dockerfile
Morphy backport of: https://github.com/ManageIQ/manageiq-pods/pull/773
Remove subscription-manager
(cherry picked from commit 196c657da322c4ee8d7406d791555345c2b73ebb)
> [MORPHY] Remove subscription manager

- images/manageiq-base/Dockerfile
Failed loading plugin "product-id": No module named 'subscription_manager.productid'
Failed loading plugin "upload-profile": cannot import name 'packageprofilelib'
Failed loading plugin "subscription-manager": cannot import name 'injection'
> Also remove the dnf plugin for subscription-manager

- manageiq-operator/deploy/olm-catalog/manageiq-operator/manifests/manageiq-operator.clusterserviceversion.yaml
- manageiq-operator/deploy/role.yaml
Based on changes in https://github.com/ManageIQ/manageiq-pods/pull/784
> We switched from using extensions to networking ingresses

- Gemfile
- manageiq-operator/pkg/helpers/miq-components/httpd.go
> gofmt -w manageiq-operator

- images/manageiq-base/Dockerfile
> Bump ubi to 8.5

- images/manageiq-base/Dockerfile
Update node version to 16
Issue:https://github.com/ManageIQ/manageiq-ui-classic/issues/7930
@miq-bot assign @Fryguy 
@miq-bot add_reviewer @Fryguy 
@miq-bot add-label dependencies
> update node version

- images/manageiq-base/Dockerfile
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7930
@miq_bot assign @fryguy
@miq_bot add_reviewer @fryguy
@miq_bot add-label dependencies, najdorf/yes?
> Downgrade node version to 14

- manageiq-operator/pkg/controller/manageiq/manageiq_controller.go
This will trigger a reconcile if the networkpolicies change
> Add watch for network policies

- manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
See also https://github.com/ManageIQ/manageiq-appliance/pull/357
> set oidc cookies to use same site

- manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
`RewriteRule ^/ping http://localhost:3001%!{(string=http)REQUEST_URI} [P,QSA,L]`
> Fix escaping

- images/manageiq-orchestrator/container-assets/entrypoint
Handle rake evm:deployment_status returning "no_database" and sleep for a bit then retry
Depends on:
> Handle a missing database in orchestrator entrypoint

- manageiq-operator/pkg/helpers/miq-components/httpd_conf.go
- these are immutable static assets
- adding packs which are also immutable static assets
- adding Cache-Control public to allow proxy servers to cache these files
This is the pod version of https://github.com/ManageIQ/manageiq-appliance/pull/358
> adding secure headers to apache

- bin/build
Also, it should be `make docker-build`
> Use bash -c to pass the environment variable

- bin/build
- manageiq-operator/Makefile
> Fix issues with podman builds and docker format

- manageiq-operator/Makefile
- Build file only contained "-"
- --format docker was not passed to docker build
Thanks @agrare
> Makefile needs shell to run shell commands

- manageiq-operator/go.mod
- manageiq-operator/go.sum
najdorf PR for https://github.com/ManageIQ/manageiq-pods/pull/867
> [najdorf] CVE 2021-3121

- lib/tasks/release.rake
Remove references to removed variables
> Fix file paths after operator-sdk upgrade

- manageiq-operator/Makefile
- manageiq-operator/config/crd/bases/manageiq.org_manageiqs.yaml
- spec/manageiq-operator/crd_spec.rb
- Fix roleName
- drop creationTimestamp and namespace from role.yaml
- remove status fron CRD since we don't set status yet
> Fix make manifests

- manageiq-operator/Dockerfile
Part of: https://github.com/ManageIQ/manageiq-pods/issues/848
> Upgrade the operator image to UBI 9

- manageiq-operator/go.mod
- manageiq-operator/go.sum
Update golang to resolve multiple CVEs on go 1.14
> [MORPHY] update golang

- images/manageiq-base/Dockerfile
~~Depends on ruby 3 support from https://github.com/ManageIQ/manageiq/pull/21531~~ MERGED 🎉 
Depends on https://github.com/ManageIQ/manageiq-rpm_build/pull/304 for ruby 3 rpm builds
> Enable ruby 3 for building images

- .github/workflows/ci.yaml
- .github/workflows/go_dependencies.yaml
Upgrade workflows to actions/checkout@v3
> Upgrade workflows to actions/checkout@v3

- manageiq-operator/api/v1alpha1/helpers/miq-components/cr.go
- manageiq-operator/api/v1alpha1/manageiq_types.go
- manageiq-operator/config/crd/bases/manageiq.org_manageiqs.yaml
Depends on: https://github.com/ManageIQ/container-memcached/pull/14
> Upgrade to UBI9 memcached image with memcached v1.6.9

- .github/workflows/build_pods.yaml
~~TODO:~~
~~- [ ] Tag builds~~ We'll do this on the build machines for now
> Add a build action

- manageiq-operator/Makefile
- manageiq-operator/go.mod
https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.25.0/
> Follow operator-sdk upgrade guide for v1.25

- manageiq-operator/api/v1alpha1/helpers/miq-components/cr.go
- manageiq-operator/api/v1alpha1/manageiq_types.go
- manageiq-operator/config/crd/bases/manageiq.org_manageiqs.yaml
Depends on:
We'll tackle the upgrade in the future.
> Change defaults to postgresql image tag 13

- .github/workflows/build_pods.yaml
https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
> Try manual workflow dispatch for build pods

- .github/workflows/build_pods.yaml
For: https://github.com/ManageIQ/manageiq/pull/22192
> Trigger monolithic container builds in the core repo

- images/manageiq-base/Dockerfile
> Remove the ansible-runner repository now that we've upgraded runner

- .github/workflows/build_pods.yaml
- .github/workflows/go_dependencies.yaml
> Update tokens for build_pods and go_dependencies workflow

- manageiq-operator/api/v1alpha1/helpers/miq-components/httpd.go
- manageiq-operator/api/v1alpha1/helpers/miq-components/kafka.go
- manageiq-operator/api/v1alpha1/helpers/miq-components/memcached.go
- manageiq-operator/api/v1alpha1/helpers/miq-components/operator.go
- manageiq-operator/api/v1alpha1/helpers/miq-components/orchestrator.go
- manageiq-operator/api/v1alpha1/helpers/miq-components/postgresql.go
- manageiq-operator/api/v1alpha1/helpers/miq-components/util.go
- AllowPrivilegeEscalation: false
- Privileged: false
- RunAsNonRoot: true
- Capabilities: Drop all
> Apply a default security context to the containers

- images/manageiq-base/Dockerfile
- images/manageiq-base/container-assets/container_env
- Prefer using $APP_ROOT (based on https://github.com/ManageIQ/manageiq-pods/pull/930#discussion_r1102969540)
- Remove the conditionals around database.yml and v2_key
- Bring back debugging defaults (bsaed on https://github.com/ManageIQ/manageiq-pods/pull/930#discussion_r1102974784)
> Followup to #930

- bin/build_hotfix
- images/manageiq-hotfix/Dockerfile
- Fix productization of FROM_IMAGE
- Ensure FROM_TAG is passed for hotfixes
- Ignore hotfixing the base image as it's not an executable image anyway
> Fix various hotfix issues

- images/manageiq-base/container-assets/clean_dnf_rpm
Otherwise it says that all packages were installed from `@System`
> Keep dnf sqlite database for installation source metadata

- manageiq-operator/Dockerfile
- manageiq-operator/go.mod
- manageiq-operator/go.sum
> Upgrade to go v1.21.0 to resolve multiple CVEs

- .github/workflows/build_pods.yaml
- .github/workflows/ci.yaml
- .github/workflows/go_dependencies.yaml
Update actions/checkout version to v4
> Update actions/checkout version to v4

- manageiq-operator/go.mod
- manageiq-operator/go.sum
Manual cherry-pick of https://github.com/ManageIQ/manageiq-pods/pull/984
> [morphy] Upgrade to go v1.21.0 to resolve multiple CVEs

- manageiq-operator/go.mod
- manageiq-operator/go.sum
`go get golang.org/x/net && go mod tidy`
> [MORPHY] Upgrade golang.org/x/net

- images/manageiq-orchestrator/container-assets/entrypoint
- manageiq-operator/api/v1alpha1/helpers/miq-components/cr.go
- make messaging deployed by default
> Deploy messaging by default

- manageiq-operator/api/v1alpha1/helpers/miq-components/kafka/kafka.go
@miq-bot add_label enhancement, quinteros/yes?
> Bump strimzi to 0.37

- images/manageiq-orchestrator/container-assets/entrypoint
- manageiq-operator/api/v1alpha1/helpers/miq-components/cr.go
Revert https://github.com/ManageIQ/manageiq-pods/pull/1024
@miq-bot add_labels quinteros/yes?, bug
@miq-bot assign @Fryguy
> Revert default messaging change

- renovate.json
@bdunne Please review. See https://docs.renovatebot.com/configuration-options/#postupdateoptions .  I'm not sure if we also need to set goModDirs option.
> Change renovate to do a go mody tidy as part of the update

- images/manageiq-base/Dockerfile
Part of: https://github.com/ManageIQ/manageiq/issues/22696
> Upgrade to ruby 3.1

- manageiq-operator/Dockerfile
> Upgrade the operator to UBI9

- bin/build
- images/manageiq-base/Dockerfile
- lib/tasks/release.rake
Part of: https://github.com/ManageIQ/manageiq-pods/issues/848
> Upgrade to UBI9

- images/manageiq-base/Dockerfile
- Fix permissions issue when trying to write to /home/manageiq/.ansible
- Enable CRB repo to remove DNF warning
> Ansible EL9 followup

- renovate.json
We already have a weekly job to update everything weekly that will include this
> Since openshift/api is riding master, it is constantly changing

- .github/workflows/ci.yaml
> Update CI to use Ruby 3.1

- images/manageiq-base/container-assets/container_env
@bdunne Please review.  The old order was confusing me, and this seems easier to follow.
> Reorder DB container_env values for readability

- images/manageiq-base/Dockerfile
- images/manageiq-webserver-worker/Dockerfile
Follow up to #1065 where manifest generation was broken.
> Fix the manifest generation by allowing it to see the local rpms

- images/manageiq-base/Dockerfile
This reverts commit 651d80b3751e9be7e6fdac6c3f1701216c52f439.
> Fix quinteros RPM repo links

- images/manageiq-base/Dockerfile
This will pull in any updates since the base image was built
Related:
- https://github.com/ManageIQ/container-httpd/pull/89
- https://github.com/ManageIQ/container-memcached/pull/27
- https://github.com/ManageIQ/container-postgresql/pull/64
> Update the base image first

- README.md
https://github.com/ManageIQ/manageiq-pods/pull/1065 changed how local you build with pre-built local RPMs, this updates the README to match.
> Fix instructions for using local RPMs

- manageiq-operator/api/v1alpha1/helpers/miq-components/opentofu_runner.go
- manageiq-operator/internal/controller/manageiq_controller.go
Creating service for opentofu runner during installation.
> Creating service for Opentofu runner

- manageiq-operator/Makefile
@bdunne Please review
cc @kbrock - this is what was causing your make manifests to have a git diff.
> Make the sed line Mac compatible

- images/manageiq-base/Dockerfile
We've been seeing build issues fetching v1.2.2
> Upgrade to dumb-init 1.2.5

- manageiq-operator/api/v1alpha1/helpers/miq-components/orchestrator.go
- manageiq-operator/api/v1alpha1/helpers/miq-components/util.go
@agrare Please review
cc @bdunne @kschanrtp
> Fix issue with pass-by-reference

- .github/workflows/ci.yaml
- images/manageiq-base/Dockerfile
For: https://github.com/ManageIQ/manageiq/pull/23142
> Switch to ruby 3.3

- images/manageiq-base/Dockerfile
https://github.com/ManageIQ/manageiq-rpm_build/pull/521
> [quinteros] Lock down to ruby 3.0.4 from Appstream

- manageiq-operator/go.mod
- manageiq-operator/go.sum
> [morphy] Upgrade protobuf to resolve CVE-2024-24786

- manageiq-operator/go.mod
> [morphy] Upgrade to go 1.23

- manageiq-operator/go.mod
- manageiq-operator/go.sum
go get golang.org/x/crypto@v0.35.0 && go mod tidy
CP4MCM-1926
> [morphy] upgrade crypto

- manageiq-operator/go.mod
> go mod tidy puts the full version

- manageiq-operator/api/v1alpha1/helpers/miq-components/httpd_conf.go
- Immediately handle requests for /api, no further processing required
- Handle websocket connections next:
- We're probably going to get more requests for notifications so handle them first
- Remote console should get less traffic, handle them next.
- Send everything else that is not handled directly by httpd to the UI pods
We previously had a bug where console sessions were being sent to the UI pods because that catch-all rewrite was being processed before the console rewrite.
> Reorder httpd route processing for efficiency and effectiveness

- manageiq-operator/config/default/metrics_service.yaml
- manageiq-operator/config/manager/manager.yaml
- manageiq-operator/config/network-policy/allow-metrics-traffic.yaml
- manageiq-operator/config/network-policy/allow-webhook-traffic.yaml
- manageiq-operator/config/prometheus/monitor.yaml
Changing the selectors is causing problems for upgrades
CP4AIOPS-18667
> Revert label changes from operator-sdk upgrade
